// Fájl: szerencsekerek_feladvanyok.js

const wheelPuzzles = [
    // Az eredeti 20 feladvány
    { category: "Közmondás", puzzle: "ADDIG JÁR A KORSÓ A KÚTRA AMÍG EL NEM TÖRIK" },
    { category: "Film & Rendező", puzzle: "QUENTIN TARANTINO PULP FICTION" },
    { category: "Élőlény", puzzle: "AZ EMBERI TEST LEGKISEBB CSILLÁMA" },
    { category: "Tárgy", puzzle: "AUTOMATA NARANCSFACSARÓ GÉP" },
    { category: "Fogalom", puzzle: "AZ IDŐ MINDENT MEGOLD" },
    { category: "Étel & Ital", puzzle: "BÉCSI SZELET KRUMPLISALÁTÁVAL" },
    { category: "Zene", puzzle: "QUEEN BOHEMIAN RHAPSODY" },
    { category: "Híres Ember", puzzle: "MUNKÁCSY MIHÁLY" },
    { category: "Földrajz", puzzle: "A MARIANNA ÁROK MÉLYSÉGE" },
    { category: "Történelem", puzzle: "A MÁSODIK VILÁGHÁBORÚ VÉGE" },
    { category: "Irodalom", puzzle: "JÓKAI MÓR AZ ARANY EMBER" },
    { category: "Sport", puzzle: "PAPP LÁSZLÓ HÁROMSZOROS OLIMPIAI BAJNOK" },
    { category: "Tudomány", puzzle: "ALBERT EINSTEIN RELATIVITÁSELMÉLETE" },
    { category: "Márkanév", puzzle: "MERCEDES BENZ" },
    { category: "Mindennapi élet", puzzle: "A BLUETOOTH CSATLAKOZTATÁSA SIKERTELEN" },
    { category: "Növény", puzzle: "JAPÁN CSERESZNYEVIRÁGZÁS" },
    { category: "Dalszöveg", puzzle: "AZÉRT VANNAK A JÓBARÁTOK" },
    { category: "Tárgy", puzzle: "ZSEBKÉS" },
    { category: "Fogalom", puzzle: "VÉGTELEN" },
    { category: "Élőlény", puzzle: "KIRÁLYPINGVIN" },

    // Új feladványok (500 db)
    // Közmondás & Szólás
    { category: "Közmondás", puzzle: "KI KORÁN KEL ARANYAT LEL" },
    { category: "Közmondás", puzzle: "JOBB FÉLNI MINT MEGIJEDNI" },
    { category: "Közmondás", puzzle: "NEM ESIK MESSZE AZ ALMA A FÁJÁTÓL" },
    { category: "Közmondás", puzzle: "AHÁNY HÁZ ANNYI SZOKÁS" },
    { category: "Közmondás", puzzle: "AJÁNDÉK LÓNAK NE NÉZD A FOGÁT" },
    { category: "Közmondás", puzzle: "SOK LÚD DISZNÓT GYŐZ" },
    { category: "Közmondás", puzzle: "A SZÜKSÉG TÖRVÉNYT BONT" },
    { category: "Közmondás", puzzle: "MINDEN CSODA HÁROM NAPIG TART" },
    { category: "Közmondás", puzzle: "AKI MÁSNAK VERMET ÁS MAGA ESIK BELE" },
    { category: "Közmondás", puzzle: "LASSÚ VÍZ PARTOT MOS" },
    { category: "Szólás", puzzle: "KÖTI AZ EBET A KARÓHOZ" },
    { category: "Szólás", puzzle: "NEM MIND ARANY AMI FÉNYLIK" },
    { category: "Szólás", puzzle: "BAGOLY MONDJA VERÉBNEK HOGY NAGYFEJŰ" },
    { category: "Szólás", puzzle: "ITT A KUTYA ELÁSVA" },
    { category: "Szólás", puzzle: "KERÜLI MINT ÖRDÖG A TÖMJÉNFÜSTÖT" },
    { category: "Szólás", puzzle: "OLAJAT ÖNT A TŰZRE" },
    { category: "Szólás", puzzle: "FÁT LEHET VÁGNI A HÁTÁN" },
    { category: "Szólás", puzzle: "EGYIK KUTYA MÁSIK EB" },
    { category: "Közmondás", puzzle: "A REST KÉTSZER FÁRAD" },
    { category: "Közmondás", puzzle: "REND A LELKE MINDENNEK" },
    { category: "Közmondás", puzzle: "SOK KICSI SOKRA MEGY" },
    { category: "Közmondás", puzzle: "A HAZUG EMBERT HAMARABB UTOLÉRIk MINT A SÁNTA KUTYÁT" },
    { category: "Szólás", puzzle: "Két legyet üt egy csapásra" },
    { category: "Közmondás", puzzle: "JOBB KÉSŐBB MINT SOHA" },
    { category: "Közmondás", puzzle: "A TÜRELEM RÓZSÁT TEREM" },

    // Film & TV
    { category: "Filmcím", puzzle: "A KERESZTAPA" },
    { category: "Filmcím", puzzle: "VISSZA A JÖVŐBE" },
    { category: "Filmcím", puzzle: "CSILLAGOK HÁBORÚJA" },
    { category: "Filmcím", puzzle: "A GYŰRŰK URA A KIRÁLY VISSZATÉR" },
    { category: "Filmcím", puzzle: "INDUL A BAKTERHÁZ" },
    { category: "Filmcím", puzzle: "A TANÚ" },
    { category: "Filmcím", puzzle: "MACSKAFOGÓ" },
    { category: "Filmcím", puzzle: "JURASSIC PARK" },
    { category: "Filmcím", puzzle: "FORREST GUMP" },
    { category: "Filmcím", puzzle: "TITANIC" },
    { category: "Filmcím", puzzle: "GLADIÁTOR" },
    { category: "Filmcím", puzzle: "A REMÉNY RABJAI" },
    { category: "Filmcím", puzzle: "HARRY POTTER ÉS A BÖLCSEK KÖVE" },
    { category: "Filmcím", puzzle: "A KARIB TENGER KALÓZAI A FEKETE GYÖNGY ÁTKA" },
    { category: "Filmcím", puzzle: "A SÖTÉT LOVAG" },
    { category: "Filmcím", puzzle: "EGY MAKULÁTLAN ELME ÖRÖK RAGYOGÁSA" },
    { category: "Filmcím", puzzle: "KONTROLL" },
    { category: "Filmcím", puzzle: "E. T. A FÖLDÖNKÍVÜLI" },
    { category: "Film & Rendező", puzzle: "STEVEN SPIELBERG RYAN KÖZLEGÉNY MEGMENTÉSE" },
    { category: "Film & Rendező", puzzle: "JAMES CAMERON AVATAR" },
    { category: "Film & Rendező", puzzle: "MARTIN SCORSESE A TÉGLA" },
    { category: "TV Sorozat", puzzle: "TRÓNOK HARCA" },
    { category: "TV Sorozat", puzzle: "BREAKING BAD TOTÁL SZÍVÁS" },
    { category: "TV Sorozat", puzzle: "JÓBARÁTOK" },
    { category: "TV Sorozat", puzzle: "A NAGY PÉNZRABLÁS" },
    { category: "TV Sorozat", puzzle: "SZEX ÉS NEW YORK" },
    { category: "Filmcím", puzzle: "AZ OROSZLÁNKIRÁLY" },
    { category: "Filmcím", puzzle: "MÁTRIX" },
    { category: "Filmcím", puzzle: "A BÁRÁNYOK HALLGATNAK" },
    { category: "Filmcím", puzzle: "CIMBORA" },
    { category: "Filmcím", puzzle: "SAUL FIA" },

    // Élőlény (Állat, Növény)
    { category: "Állat", puzzle: "AFRIKAI ELEFÁNT" },
    { category: "Állat", puzzle: "SZIBÉRIAI TIGRIS" },
    { category: "Állat", puzzle: "NAGY FEHÉR CÁPA" },
    { category: "Állat", puzzle: "MAGYAR VIZSLA" },
    { category: "Állat", puzzle: "KÉK BÁLNA" },
    { category: "Állat", puzzle: "BARNA MEDVE" },
    { category: "Állat", puzzle: "VÖRÖS PANDA" },
    { category: "Állat", puzzle: "CSÁSZÁRPINGVIN" },
    { category: "Állat", puzzle: "GRIZZLY MEDVE" },
    { category: "Állat", puzzle: "HÓPÁRDUC" },
    { category: "Állat", puzzle: "FEHÉR GÓLYA" },
    { category: "Állat", puzzle: "KOVÁCS BÉLA" },
    { category: "Állat", puzzle: "KOMODI SÁRKÁNY" },
    { category: "Növény", puzzle: "FEHÉR AKÁC" },
    { category: "Növény", puzzle: "ERDEI FENYŐ" },
    { category: "Növény", puzzle: "TAVIRÓZSA" },
    { category: "Növény", puzzle: "NAPRAFORGÓ" },
    { category: "Növény", puzzle: "GYÖNGYVIRÁG" },
    { category: "Növény", puzzle: "KAMILLA" },
    { category: "Növény", puzzle: "BÚZAVIRÁG" },
    { category: "Növény", puzzle: "LEVENDULA" },
    { category: "Növény", puzzle: "Fekete nadálytő" },
    { category: "Növény", puzzle: "HÚSEVŐ NÖVÉNY" },
    { category: "Élőlény", puzzle: "VILÁGÍTÓ MEDÚZA" },
    { category: "Élőlény", puzzle: "LÉGYÖLŐ GALÓCA" },
    { category: "Élőlény", puzzle: "PÁFRÁNYFENYŐ" },

    // Tárgy
    { category: "Tárgy", puzzle: "VEZETÉK NÉLKÜLI FÜLHALLGATÓ" },
    { category: "Tárgy", puzzle: "OKOSTELEFON TÖLTŐKÁBEL" },
    { category: "Tárgy", puzzle: "ROZSDAMENTES ACÉL VILLA" },
    { category: "Tárgy", puzzle: "ÍRÓASZTALI LÁMPA" },
    { category: "Tárgy", puzzle: "MIKROHULLÁMÚ SÜTŐ" },
    { category: "Tárgy", puzzle: "ELEKTROMOS FOGKEFE" },
    { category: "Tárgy", puzzle: "DIGITÁLIS FÉNYKÉPEZŐGÉP" },
    { category: "Tárgy", puzzle: "NAPELEMES ZSEBLÁMPA" },
    { category: "Tárgy", puzzle: "MEMÓRIAHABOS MATRAC" },
    { category: "Tárgy", puzzle: "KERÁMIA FŐZŐLAP" },
    { category: "Tárgy", puzzle: "GOLYÓSTOLL" },
    { category: "Tárgy", puzzle: "BICIKLILAKAT" },
    { category: "Tárgy", puzzle: "HÁTIZSÁK" },
    { category: "Tárgy", puzzle: "DUGÓHÚZÓ" },
    { category: "Tárgy", puzzle: "ESERNYŐ" },
    { category: "Tárgy", puzzle: "KÖNYVESPOLC" },
    { category: "Tárgy", puzzle: "PERZSA SZŐNYEG" },
    { category: "Tárgy", puzzle: "LEGO KOCKA" },
    { category: "Tárgy", puzzle: "RUBIK KOCKA" },
    { category: "Tárgy", puzzle: "FALIÓRA" },
    { category: "Tárgy", puzzle: "MOSOGATÓGÉP TABLETTA" },
    { category: "Tárgy", puzzle: "TÁVIRÁNYÍTÓ" },
    { category: "Tárgy", puzzle: "KÁVÉFŐZŐ" },
    { category: "Tárgy", puzzle: "Porszívó" },
    { category: "Tárgy", puzzle: "VASALÓDESZKA" },

    // Fogalom
    { category: "Fogalom", puzzle: "A SZERETET EREJE" },
    { category: "Fogalom", puzzle: "TUDOMÁNYOS FANTASZTIKUM" },
    { category: "Fogalom", puzzle: "VÉLETLEN EGYBEESÉS" },
    { category: "Fogalom", puzzle: "KRITIKUS GONDOLKODÁS" },
    { category: "Fogalom", puzzle: "FENNTARTHATÓ FEJLŐDÉS" },
    { category: "Fogalom", puzzle: "GLOBÁLIS FELMELEGEDÉS" },
    { category: "Fogalom", puzzle: "MESTERSÉGES INTELLIGENCIA" },
    { category: "Fogalom", puzzle: "KÖZÖSSÉGI MÉDIA" },
    { category: "Fogalom", puzzle: "Kvantummechanika" },
    { category: "Fogalom", puzzle: "GENERÁCIÓS SZAKADÉK" },
    { category: "Fogalom", puzzle: "A TÖMEGVONZÁS TÖRVÉNYE" },
    { category: "Fogalom", puzzle: "KULTURÁLIS ÖRÖKSÉG" },
    { category: "Fogalom", puzzle: "DEMOKRÁCIA" },
    { category: "Fogalom", puzzle: "SZÓLÁSSZABADSÁG" },
    { category: "Fogalom", puzzle: "DEJA VU ÉRZÉS" },
    { category: "Fogalom", puzzle: "KÉPZELET" },
    { category: "Fogalom", puzzle: "A VÉGTELEN TÖRTÉNET" },
    { category: "Fogalom", puzzle: "A JÓ ÉS A ROSSZ HARCA" },
    { category: "Fogalom", puzzle: "EMBERI JOGOK" },
    { category: "Fogalom", puzzle: "POLITIKAI KORREKTSÉG" },
    { category: "Fogalom", puzzle: "A PILLANGÓ HATÁS" },
    { category: "Fogalom", puzzle: "ÁLLAMPOLGÁRI JOG" },
    { category: "Fogalom", puzzle: "A SORS IRONIÁJA" },
    { category: "Fogalom", puzzle: "A LEGKISEBB KÖZÖS TÖBBSZÖRÖS" },
    { category: "Fogalom", puzzle: "Belső béke" },
    { category: "Fogalom", puzzle: "Munka és magánélet egyensúlya" },
    { category: "Fogalom", puzzle: "Nulla tolerancia" },

    // Étel & Ital
    { category: "Étel & Ital", puzzle: "GULYÁSLEVES CSIPETKÉVEL" },
    { category: "Étel & Ital", puzzle: "TÖLTÖTT KÁPOSZTA TEJFÖLLEL" },
    { category: "Étel & Ital", puzzle: "DOBOS TORTA" },
    { category: "Étel & Ital", puzzle: "SOMLÓI GALUSKA" },
    { category: "Étel & Ital", puzzle: "EGRI BIKAVÉR" },
    { category: "Étel & Ital", puzzle: "HALÁSZLÉ" },
    { category: "Étel & Ital", puzzle: "KÜRTŐSKALÁCS" },
    { category: "Étel & Ital", puzzle: "TÚRÓS CSUSZA SZALONNÁVAL" },
    { category: "Étel & Ital", puzzle: "CSIRKEPAPRIKÁS NOKEDLIVEL" },
    { category: "Étel & Ital", puzzle: "LANGOS SAJTTAL ÉS TEJFÖLLEL" },
    { category: "Étel & Ital", puzzle: "MÁKOS GUBA" },
    { category: "Étel & Ital", puzzle: "RAKOTT KRUMPLI" },
    { category: "Étel & Ital", puzzle: "PÖRKÖLT" },
    { category: "Étel & Ital", puzzle: "TOKAJI ASZÚ" },
    { category: "Étel & Ital", puzzle: "PALACSINTA" },
    { category: "Étel & Ital", puzzle: "HÚSLEVES CSIGATÉSZTÁVAL" },
    { category: "Étel & Ital", puzzle: "BABLEVES FÜSTÖLT CSÜLÖKKEL" },
    { category: "Étel & Ital", puzzle: "TEPERTŐS POGÁCSA" },
    { category: "Étel & Ital", puzzle: "ARANYGALUSKA VANÍLIAÖNTETTEL" },
    { category: "Étel & Ital", puzzle: "BRASSÓI APRÓPECSENYE" },
    { category: "Étel & Ital", puzzle: "HORTBÁGYI HÚSOS PALACSINTA" },
    { category: "Étel & Ital", puzzle: "PÁLINKA" },
    { category: "Étel & Ital", puzzle: "ZSERBÓ SZELET" },
    { category: "Étel & Ital", puzzle: "LECSÓ" },
    { category: "Étel & Ital", puzzle: "FŐZELÉK FASÍRTTAL" },

    // Zene
    { category: "Zene", puzzle: "PRESSER GÁBOR" },
    { category: "Zene", puzzle: "TANKCSAPDA" },
    { category: "Zene", puzzle: "HALOTT PÉNZ" },
    { category: "Zene", puzzle: "LISZT FERENC" },
    { category: "Zene", puzzle: "BARTÓK BÉLA" },
    { category: "Zene", puzzle: "LGT EGYÜTTES" },
    { category: "Zene", puzzle: "QUIMBY" },
    { category: "Zene", puzzle: "EDDA MŰVEK" },
    { category: "Zene", puzzle: "KODÁLY ZOLTÁN" },
    { category: "Zene", puzzle: "RÚZSA MAGDI" },
    { category: "Zene", puzzle: "PUNNANY MASSIF" },
    { category: "Zene", puzzle: "WELLHELLO" },
    { category: "Zene", puzzle: "MAJKA" },
    { category: "Dalszöveg", puzzle: "MOST MÚLIK PONTOSAN" },
    { category: "Dalszöveg", puzzle: "NÉLKÜLED" },
    { category: "Dalszöveg", puzzle: "AZ ÉLET SZÉP TE CSODÁS" },
    { category: "Dalszöveg", puzzle: "AFRIKA" },
    { category: "Dalszöveg", puzzle: "SZÁLLJ FEL SZABAD MADÁR" },
    { category: "Dalszöveg", puzzle: "A ZENE AZ KELL" },
    { category: "Zeneszerző", puzzle: "WOLFGANG AMADEUS MOZART" },
    { category: "Zeneszerző", puzzle: "LUDWIG VAN BEETHOVEN" },
    { category: "Együttes", puzzle: "THE BEATLES" },
    { category: "Együttes", puzzle: "METALLICA" },
    { category: "Együttes", puzzle: "ABBA" },
    { category: "Együttes", puzzle: "NIRVANA" },

    // Híres Ember
    { category: "Híres Ember", puzzle: "PETŐFI SÁNDOR" },
    { category: "Híres Ember", puzzle: "KOSSUTH LAJOS" },
    { category: "Híres Ember", puzzle: "SEMMELWEIS IGNÁC" },
    { category: "Híres Ember", puzzle: "PUSKÁS FERENC" },
    { category: "Híres Ember", puzzle: "SZENT ISTVÁN KIRÁLY" },
    { category: "Híres Ember", puzzle: "HUNYADI MÁTYÁS" },
    { category: "Híres Ember", puzzle: "LEONARDO DA VINCI" },
    { category: "Híres Ember", puzzle: "MARIE CURIE" },
    { category: "Híres Ember", puzzle: "NELSON MANDELA" },
    { category: "Híres Ember", puzzle: "ARANY JÁNOS" },
    { category: "Híres Ember", puzzle: "ADY ENDRE" },
    { category: "Híres Ember", puzzle: "WILLIAM SHAKESPEARE" },
    { category: "Híres Ember", puzzle: "GALILEO GALILEI" },
    { category: "Híres Ember", puzzle: "MARTIN LUTHER KING" },
    { category: "Híres Ember", puzzle: "SZÉCHENYI ISTVÁN" },
    { category: "Híres Ember", puzzle: "DEÁK FERENC" },
    { category: "Híres Ember", puzzle: "NEUMANN JÁNOS" },
    { category: "Híres Ember", puzzle: "SZENT-GYÖRGYI ALBERT" },
    { category: "Híres Ember", puzzle: "CSERHALMI GYÖRGY" },
    { category: "Híres Ember", puzzle: "BODROGI GYULA" },
    { category: "Híres Ember", puzzle: "BUDAI ILONA" },
    { category: "Híres Ember", puzzle: "Gábor Dénes" },
    { category: "Híres Ember", puzzle: "RUBIK ERNŐ" },
    { category: "Híres Ember", puzzle: "TERÉZ ANYA" },
    { category: "Híres Ember", puzzle: "STEVE JOBS" },
    { category: "Híres Ember", puzzle: "ELON MUSK" },

    // Földrajz
    { category: "Földrajz", puzzle: "DUNA TISZA KÖZE" },
    { category: "Földrajz", puzzle: "A VILÁG LEGMAGASABB HEGYCSÚCSA" },
    { category: "Földrajz", puzzle: "BUDAPEST FŐVÁROS" },
    { category: "Földrajz", puzzle: "A BALATON ÁTLAGOS VÍZMÉLYSÉGE" },
    { category: "Földrajz", puzzle: "AMAZONAS ESŐERDŐ" },
    { category: "Földrajz", puzzle: "SZAHARA SIVATAG" },
    { category: "Földrajz", puzzle: "NÍLUS FOLYÓ" },
    { category: "Földrajz", puzzle: "MOUNT EVEREST" },
    { category: "Földrajz", puzzle: "KÁRPÁT MEDENCE" },
    { category: "Földrajz", puzzle: "HORTOBÁGYI NEMZETI PARK" },
    { category: "Földrajz", puzzle: "AGGTELEKI CSEPPKŐBARLANG" },
    { category: "Földrajz", puzzle: "A KÍNAI NAGY FAL" },
    { category: "Földrajz", puzzle: "NAGY KORALLZÁTONY" },
    { category: "Földrajz", puzzle: "TISZA TÓ" },
    { category: "Földrajz", puzzle: "FERTŐ TÓ" },
    { category: "Földrajz", puzzle: "CSEHORSZÁG FŐVÁROSA PRÁGA" },
    { category: "Földrajz", puzzle: "FRANCIAORSZÁG" },
    { category: "Földrajz", puzzle: "JAPÁN" },
    { category: "Földrajz", puzzle: "EGYESÜLT ÁLLAMOK" },
    { category: "Földrajz", puzzle: "OROSZORSZÁG" },
    { category: "Földrajz", puzzle: "KÉKESTETŐ" },
    { category: "Földrajz", puzzle: "CSENDES ÓCEÁN" },
    { category: "Földrajz", puzzle: "ATLANTI ÓCEÁN" },
    { category: "Földrajz", puzzle: "Északi sark" },
    { category: "Földrajz", puzzle: "DÉLI SARK" },

    // Történelem
    { category: "Történelem", puzzle: "A HONFOGLALÁS KORA" },
    { category: "Történelem", puzzle: "AZ EZERNYOLCSZÁZNEGYVENNYOLCAS FORRADALOM" },
    { category: "Történelem", puzzle: "A BERLINI FAL LEOMBLÁSA" },
    { category: "Történelem", puzzle: "AZ ÓKORI RÓMA" },
    { category: "Történelem", puzzle: "A KÖZÉPKOR" },
    { category: "Történelem", puzzle: "AZ AMERIKAI FÜGGETLENSÉGI HÁBORÚ" },
    { category: "Történelem", puzzle: "A FRANCIA FORRADALOM" },
    { category: "Történelem", puzzle: "AZ ELSŐ VILÁGHÁBORÚ" },
    { category: "Történelem", puzzle: "A NÁNDORFEHÉRVÁRI DIADAL" },
    { category: "Történelem", puzzle: "A MUHACSI CSATA" },
    { category: "Történelem", puzzle: "TRIANONI BÉKESZERZŐDÉS" },
    { category: "Történelem", puzzle: "A HIDEGHÁBORÚ" },
    { category: "Történelem", puzzle: "A HOLDRA SZÁLLÁS" },
    { category: "Történelem", puzzle: "AZ ÓKORI EGYIPTOM" },
    { category: "Történelem", puzzle: "VIKING KOR" },
    { category: "Történelem", puzzle: "A RÓMAI BIRODALOM BUKÁSA" },
    { category: "Történelem", puzzle: "A REFORMÁCIÓ" },
    { category: "Történelem", puzzle: "AZ ARANYBULLA" },
    { category: "Történelem", puzzle: "AZ IPARI FORRADALOM" },
    { category: "Történelem", puzzle: "A RÁKÓCZI SZABADSÁGHARC" },
    { category: "Történelem", puzzle: "A KIEGYEZÉS" },
    { category: "Történelem", puzzle: "A POZSONYI CSATA" },
    { category: "Történelem", puzzle: "A TITANIC ELSÜLLYEDÉSE" },
    { category: "Történelem", puzzle: "A RENESZÁNSZ KORA" },
    { category: "Történelem", puzzle: "A felvilágosodás" },

    // Irodalom
    { category: "Irodalom", puzzle: "MOLNÁR FERENC A PÁL UTCAI FIÚK" },
    { category: "Irodalom", puzzle: "GÁRDONYI GÉZA EGRI CSILLAGOK" },
    { category: "Irodalom", puzzle: "MÓRICZ ZSIGMOND LÉGY JÓ MINDHALÁLIG" },
    { category: "Irodalom", puzzle: "ARANY JÁNOS TOLDI" },
    { category: "Irodalom", puzzle: "MIKSZÁTH KÁLMÁN A FEKETE VÁROS" },
    { category: "Irodalom", puzzle: "MADÁCH IMRE AZ EMBER TRAGÉDIÁJA" },
    { category: "Irodalmi Szereplő", puzzle: "NEMECSEK ERNŐ" },
    { category: "Irodalmi Szereplő", puzzle: "ROMEO ÉS JÚLIA" },
    { category: "Irodalmi Szereplő", puzzle: "HARRY POTTER" },
    { category: "Irodalmi Szereplő", puzzle: "SHERLOCK HOLMES" },
    { category: "Irodalom", puzzle: "FEKETE ISTVÁN VUK" },
    { category: "Irodalom", puzzle: "GEORGE ORWELL EZERKILENCSZÁZNYOLCVANNÉGY" },
    { category: "Irodalom", puzzle: "JANE AUSTEN BÜSZKESÉG ÉS BALÍTÉLET" },
    { category: "Irodalom", puzzle: "ANTOINE DE SAINT EXUPÉRY A KIS HERCEG" },
    { category: "Irodalom", puzzle: "ÖRKÉNY ISTVÁN EGYPERCES NOVELLÁK" },
    { category: "Irodalom", puzzle: "JÓZSEF ATTILA" },
    { category: "Irodalom", puzzle: "RADNÓTI MIKLÓS" },
    { category: "Irodalom", puzzle: "KERTÉSZ IMRE SORSTALANSÁG" },
    { category: "Irodalom", puzzle: "HOMÉROSZ ILIÁSZ" },
    { category: "Irodalom", puzzle: "DANTE ALIGHIERI ISTENI SZÍNJÁTÉK" },
    { category: "Költemény", puzzle: "A NEMZETI DAL" },
    { category: "Költemény", puzzle: "A WALESI BÁRDOK" },
    { category: "Irodalom", puzzle: "A NAGY GATSBY" },
    { category: "Irodalom", puzzle: "ZABHEGYEZŐ" },
    { category: "Irodalom", puzzle: "SZABÓ MAGDA AZ AJTÓ" },

    // Sport
    { category: "Sport", puzzle: "MAGYAR VÍZILABDA VÁLOGATOTT" },
    { category: "Sport", puzzle: "FORMA EGY MAGYAR NAGYDÍJ" },
    { category: "Sport", puzzle: "OLIMPIAI JÁTÉKOK" },
    { category: "Sport", puzzle: "HOSSZÚ KATINKA IRON LADY" },
    { category: "Sport", puzzle: "SZOBOSZLAI DOMINIK" },
    { category: "Sport", puzzle: "ARANYCSAPAT" },
    { category: "Sport", puzzle: "BAJNOKOK LIGÁJA" },
    { category: "Sport", puzzle: "LABDARÚGÓ VILÁGBAJNOKSÁG" },
    { category: "Sport", puzzle: "TOUR DE FRANCE" },
    { category: "Sport", puzzle: "WIMBLEDONI TENISZBAJNOKSÁG" },
    { category: "Sport", puzzle: "MICHAEL JORDAN" },
    { category: "Sport", puzzle: "ROGER FEDERER" },
    { category: "Sport", puzzle: "USAIN BOLT" },
    { category: "Sport", puzzle: "EGERSI KRISZTINA" },
    { category: "Sportág", puzzle: "KÉZILABDA" },
    { category: "Sportág", puzzle: "ÚSZÁS" },
    { category: "Sportág", puzzle: "JÉGKORONG" },
    { category: "Sportág", puzzle: "ATLÉTIKA" },
    { category: "Sport", puzzle: "SUPER BOWL" },
    { category: "Sport", puzzle: "KOVÁCS KATALIN" },
    { category: "Sport", puzzle: "BERKI KRISZTIÁN" },
    { category: "Sport", puzzle: "SZILÁGYI ÁRON" },
    { category: "Sport", puzzle: "A TESTNEVELÉS ÓRA" },
    { category: "Sport", puzzle: "LEWIS HAMILTON" },
    { category: "Sport", puzzle: "LIONEL MESSI" },

    // Tudomány
    { category: "Tudomány", puzzle: "A FÉNY SEBESSÉGE" },
    { category: "Tudomány", puzzle: "CHARLES DARWIN EVOLÚCIÓELMÉLETE" },
    { category: "Tudomány", puzzle: "A DNS KETTŐS SPIRÁL" },
    { category: "Tudomány", puzzle: "A VÍZ FORRÁSPONTJA" },
    { category: "Tudomány", puzzle: "ISAAC NEWTON" },
    { category: "Tudomány", puzzle: "NIKOLA TESLA" },
    { category: "Tudomány", puzzle: "STEPHEN HAWKING" },
    { category: "Tudomány", puzzle: "A PITAGORASZ TÉTEL" },
    { category: "Tudomány", puzzle: "FEKETE LYUK" },
    { category: "Tudomány", puzzle: "NAPRENDSZER" },
    { category: "Tudomány", puzzle: "TEJÚTRENDSZER" },
    { category: "Tudomány", puzzle: "ATOMENERGIA" },
    { category: "Tudomány", puzzle: "PERIÓDUSOS RENDSZER" },
    { category: "Tudomány", puzzle: "FOTOSZINTÉZIS" },
    { category: "Tudomány", puzzle: "ANTIBIOTIKUM" },
    { category: "Tudomány", puzzle: "GÉNTECHNOLÓGIA" },
    { category: "Tudomány", puzzle: "KLÍMAVÁLTOZÁS" },
    { category: "Tudomány", puzzle: "A HANG SEBESSÉGE" },
    { category: "Tudomány", puzzle: "A NEGYEDIK DIMENZIÓ" },
    { category: "Tudomány", puzzle: "A NAGY BUMM ELMÉLETE" },
    { category: "Tudomány", puzzle: "PENICILLIN" },
    { category: "Tudomány", puzzle: "A TERMÉSZETES KIVÁLASZTÓDÁS" },
    { category: "Tudomány", puzzle: "SÖTÉT ANYAG" },
    { category: "Tudomány", puzzle: "FÖLDRENGÉS" },
    { category: "Tudomány", puzzle: "VULKÁNI KITÖRÉS" },

    // Márkanév
    { category: "Márkanév", puzzle: "PICK SZEGED" },
    { category: "Márkanév", puzzle: "TÚRÓ RUDI" },
    { category: "Márkanév", puzzle: "COCA COLA" },
    { category: "Márkanév", puzzle: "LEGO" },
    { category: "Márkanév", puzzle: "IKEA" },
    { category: "Márkanév", puzzle: "MCDONALDS" },
    { category: "Márkanév", puzzle: "GOOGLE" },
    { category: "Márkanév", puzzle: "FACEBOOK" },
    { category: "Márkanév", puzzle: "APPLE" },
    { category: "Márkanév", puzzle: "SAMSUNG" },
    { category: "Márkanév", puzzle: "NIKE" },
    { category: "Márkanév", puzzle: "ADIDAS" },
    { category: "Márkanév", puzzle: "ZARA" },
    { category: "Márkanév", puzzle: "MOL" },
    { category: "Márkanév", puzzle: "OTP BANK" },
    { category: "Márkanév", puzzle: "GYŐRI KEKSZ" },
    { category: "Márkanév", puzzle: "HERENDI PORCELÁN" },
    { category: "Márkanév", puzzle: "ZSOLNAY PORCELÁN" },
    { category: "Márkanév", puzzle: "UNICUM" },
    { category: "Márkanév", puzzle: "SOPRONI" },
    { category: "Márkanév", puzzle: "BORSODI" },
    { category: "Márkanév", puzzle: "MICROSOFT WINDOWS" },
    { category: "Márkanév", puzzle: "TESLA" },
    { category: "Márkanév", puzzle: "AMAZON" },
    { category: "Márkanév", puzzle: "NETFLIX" },

    // Mindennapi élet
    { category: "Mindennapi élet", puzzle: "NEM MŰKÖDIK AZ INTERNET" },
    { category: "Mindennapi élet", puzzle: "LEMERÜLT A TELEFONOM AKKUMULÁTORA" },
    { category: "Mindennapi élet", puzzle: "HOL HAGYTAM A KULCSOMAT" },
    { category: "Mindennapi élet", puzzle: "MIT ESZÜNK MA VACSORÁRA" },
    { category: "Mindennapi élet", puzzle: "ELFOGYOTT A KÁVÉ" },
    { category: "Mindennapi élet", puzzle: "KÉREK EGY SZÁMLÁT" },
    { category: "Mindennapi élet", puzzle: "MERRE VAN A LEGKÖZELEBBI MOSDÓ" },
    { category: "Mindennapi élet", puzzle: "JÓ REGGELT KÍVÁNOK" },
    { category: "Mindennapi élet", puzzle: "BEZÁRT A BOLT" },
    { category: "Mindennapi élet", puzzle: "ELFELEJTETTEM A JELSZAVAMAT" },
    { category: "Mindennapi élet", puzzle: "KÉSÉSSEL KÖZLEKEDIK A VONAT" },
    { category: "Mindennapi élet", puzzle: "NINCS ITTHON KENYÉR" },
    { category: "Mindennapi élet", puzzle: "VIGYÉL ESERNYŐT MERT ESNI FOG" },
    { category: "Mindennapi élet", puzzle: "FELHÍVLAK KÉSŐBB" },
    { category: "Mindennapi élet", puzzle: "LE KÉNE VINNI A SZEMETET" },
    { category: "Mindennapi élet", puzzle: "MEGINT FORGALMI DUGÓ VAN" },
    { category: "Mindennapi élet", puzzle: "BANKKÁRTYÁVAL SZERETNÉK FIZETNI" },
    { category: "Mindennapi élet", puzzle: "ELNÉZÉST A ZAVARÁSÉRT" },
    { category: "Mindennapi élet", puzzle: "KAPCSOLD KI A TELEFONT" },
    { category: "Mindennapi élet", puzzle: "MINDJÁRT KÉSZ A VACSORA" },
    { category: "Mindennapi élet", puzzle: "BE KELL VÁSÁROLNI" },
    { category: "Mindennapi élet", puzzle: "HOVÁ TEGYEM A KABÁTOM" },
    { category: "Mindennapi élet", puzzle: "MILYEN IDŐ VAN KINT" },
    { category: "Mindennapi élet", puzzle: "BOLDOG SZÜLETÉSNAPOT" },
    { category: "Mindennapi élet", puzzle: "BÉKÉS BOLDOG KARÁCSONYT" },
    
    // Vegyes Kategóriák
    { category: "Művészet", puzzle: "A MONA LISA" },
    { category: "Művészet", puzzle: "MICHELANGELO DÁVID SZOBRA" },
    { category: "Művészet", puzzle: "VINCENT VAN GOGH CSILLAGOS ÉJ" },
    { category: "Művészet", puzzle: "CSOTVÁRY KOSZTKA TIVADAR MAGÁNYOS CÉDRUS" },
    { category: "Épület", puzzle: "AZ ORSZÁGHÁZ" },
    { category: "Épület", puzzle: "A PÁRIZSI EIFFEL TORONY" },
    { category: "Épület", puzzle: "A PISAI FERDE TORONY" },
    { category: "Épület", puzzle: "A RÓMAI COLOSSEUM" },
    { category: "Foglalkozás", puzzle: "ŰRHAJÓS" },
    { category: "Foglalkozás", puzzle: "TŰZOLTÓ" },
    { category: "Foglalkozás", puzzle: "ORVOS" },
    { category: "Foglalkozás", puzzle: "TANÁR" },
    { category: "Foglalkozás", puzzle: "PROGRAMOZÓ" },
    { category: "Foglalkozás", puzzle: "PÉK" },
    { category: "Foglalkozás", puzzle: "VILLANYSZERELŐ" },
    { category: "Rendezvény", puzzle: "SZIGET FESZTIVÁL" },
    { category: "Rendezvény", puzzle: "A VELENCEI KARNEVÁL" },
    { category: "Rendezvény", puzzle: "OKTÓBERFESZT" },
    { category: "Rendezvény", puzzle: "MOHÁCSI BUSÓJÁRÁS" },
    { category: "Csillagászat", puzzle: "ANDROMÉDA GALAXIS" },
    { category: "Csillagászat", puzzle: "A NAGY MEDVE CSILLAGKÉP" },
    { category: "Csillagászat", puzzle: "HALLEY ÜSTÖKÖS" },
    { category: "Hivatal", puzzle: "KORMÁNYABLAK" },
    { category: "Hivatal", puzzle: "NEMZETI ADÓ ÉS VÁMHIVATAL" },
    { category: "Jármű", puzzle: "GŐZMOZDONY" },
    { category: "Jármű", puzzle: "HŐLÉGBALLON" },
    { category: "Jármű", puzzle: "TENGERALATTJÁRÓ" },
    { category: "Jármű", puzzle: "ELEKTROMOS ROLLER" },
    { category: "Hobbi", puzzle: "BÉLYEGGYŰJTÉS" },
    { category: "Hobbi", puzzle: "Horgászat" },
    { category: "Hobbi", puzzle: "MAKETTKÉSZÍTÉS" },
    { category: "Hobbi", puzzle: "FOTÓZÁS" },
    { category: "Testrész", puzzle: "EMBERI AGY" },
    { category: "Testrész", puzzle: "VAKBÉL" },
    { category: "Testrész", puzzle: "A SZÍV KAMRÁI ÉS PITVARAI" },
    { category: "Mitològia", puzzle: "ZEUSZ A FŐISTEN" },
    { category: "Mitològia", puzzle: "A TRÓJAI FALÓ" },
    { category: "Mitològia", puzzle: "ODÜSSZEUSZ" },
    { category: "Mese", puzzle: "HÓFEHÉRKE ÉS A HÉT TÖRPE" },
    { category: "Mese", puzzle: "PIROSKA ÉS A FARKAS" },
    { category: "Mese", puzzle: "A KIS GÖMBÖC" },
    { category: "Mese", puzzle: "MAGYAR NÉPMESÉK" },
    { category: "Mesehős", puzzle: "Frakk a macskák réme" },
    { category: "Mesehős", puzzle: "VUK" },
    { category: "Mesehős", puzzle: "Mekk Elek az ezermester" },
    { category: "Mesehős", puzzle: "Süsü a sárkány" },
    { category: "Mesehős", puzzle: "Dr Bubó" },
    { category: "Színész", puzzle: "LŐTE ATTILA" },
    { category: "Színész", puzzle: "TÖRŐCSIK MARI" },
    { category: "Színész", puzzle: "LATINOVITS ZOLTÁN" },
    { category: "Színész", puzzle: "KERN ANDRÁS" },
    { category: "Színész", puzzle: "BUD SPENCER ÉS TERENCE HILL" },
    { category: "Színész", puzzle: "TOM HANKS" },
    { category: "Színész", puzzle: "MERYL STREEP" },
    { category: "Színész", puzzle: "JOHNNY DEPP" },
    { category: "Politika", puzzle: "EURÓPAI PARLAMENT" },
    { category: "Politika", puzzle: "EGYESÜLT NEMZETEK SZERVEZETE" },
    { category: "Politika", puzzle: "MINISZTERELNÖK" },
    { category: "Politika", puzzle: "KÖZTÁRSASÁGI ELNÖK" },
    { category: "Betegség", puzzle: "MEGFÁZÁS ÉS INFLUENZA" },
    { category: "Betegség", puzzle: "ALLERGIÁS REAKCIÓ" },
    { category: "Kémia", puzzle: "HIDROGÉN PEROXID" },
    { category: "Kémia", puzzle: "NÁTRIUM KLORID" },
    { category: "Kémia", puzzle: "SZÉNSAV" },
    { category: "Eszköz", puzzle: "CSAVARHÚZÓ KÉSZLET" },
    { category: "Eszköz", puzzle: "SVÁJCI BICSKA" },
    { category: "Fiktív Helyszín", puzzle: "KÖZÉPFÖLDE" },
    { category: "Fiktív Helyszín", puzzle: "WESTEROS" },
    { category: "Fiktív Helyszín", puzzle: "TATOOINE" },
    { category: "Fiktív Helyszín", puzzle: "ROXFORT" },
    { category: "Mondóka", puzzle: "SÜSS FEL NAP FÉNYES NAP" },
    { category: "Mondóka", puzzle: "EC PEC KIMEHETSZ" },
    { category: "Számítástechnika", puzzle: "OPERÁCIÓS RENDSZER" },
    { category: "Számítástechnika", puzzle: "PROGRAMOZÁSI NYELV" },
    { category: "Számítástechnika", puzzle: "FELHŐ ALAPÚ SZOLGÁLTATÁS" },
    { category: "Természeti jelenség", puzzle: "SZIVÁRVÁNY" },
    { category: "Természeti jelenség", puzzle: "TELJES NAPFOGYATKOZÁS" },
    { category: "Természeti jelenség", puzzle: "ÉSZAKI FÉNY" },
    { category: "Játék", puzzle: "MONOPOLY TÁRSASJÁTÉK" },
    { category: "Játék", puzzle: "SAKK" },
    { category: "Játék", puzzle: "MAGYAR KÁRTYA" },
    { category: "Játék", puzzle: "AKTIVITY" },
    { category: "TV Műsor", puzzle: "SZERENCSEKERÉK" },
    { category: "TV Műsor", puzzle: "SZERENCSESZOMBAT" },
    { category: "TV Műsor", puzzle: "AZ ÉV HOTELE" },
    { category: "TV Műsor", puzzle: "HÍRADÓ" }
];
