// Fájl: szerencsekerek_feladvanyok.js

const wheelPuzzles = [
    // Eredeti 20 feladvány
    { category: "Közmondás", puzzle: "ADDIG JÁR A KORSÓ A KÚTRA AMÍG EL NEM TÖRIK" },
    { category: "Film & Rendező", puzzle: "QUENTIN TARANTINO PULP FICTION" },
    { category: "Élőlény", puzzle: "AZ EMBERI TEST LEGKISEBB CSILLÁMA" },
    { category: "Tárgy", puzzle: "AUTOMATA NARANCSFACSARÓ GÉP" },
    { category: "Fogalom", puzzle: "AZ IDŐ MINDENT MEGOLD" },
    { category: "Étel & Ital", puzzle: "BÉCSI SZELET KRUMPLISALÁTÁVAL" },
    { category: "Zene", puzzle: "QUEEN BOHEMIAN RHAPSODY" },
    { category: "Híres Ember", puzzle: "MUNKÁCSY MIHÁLY" },
    { category: "Földrajz", puzzle: "A MARIANNA ÁROK MÉLYSÉGE" },
    { category: "Történelem", puzzle: "A MÁSODIK VILÁGHÁBORÚ VÉGE" },
    { category: "Irodalom", puzzle: "JÓKAI MÓR AZ ARANY EMBER" },
    { category: "Sport", puzzle: "PAPP LÁSZLÓ HÁROMSZOROS OLIMPIAI BAJNOK" },
    { category: "Tudomány", puzzle: "ALBERT EINSTEIN RELATIVITÁSELMÉLETE" },
    { category: "Márkanév", puzzle: "MERCEDES BENZ" },
    { category: "Mindennapi élet", puzzle: "A BLUETOOTH CSATLAKOZTATÁSA SIKERTELEN" },
    { category: "Növény", puzzle: "JAPÁN CSERESZNYEVIRÁGZÁS" },
    { category: "Dalszöveg", puzzle: "AZÉRT VANNAK A JÓBARÁTOK" },
    { category: "Tárgy", puzzle: "ZSEBKÉS" },
    { category: "Fogalom", puzzle: "VÉGTELEN" },
    { category: "Élőlény", puzzle: "KIRÁLYPINGVIN" },

    // --- ÚJ FELADVÁNYOK ---

    // Kategória: Közmondás
    { category: "Közmondás", puzzle: "KI KORÁN KEL ARANYAT LEL" },
    { category: "Közmondás", puzzle: "JOBB FÉLNI MINT MEGIJEDNI" },
    { category: "Közmondás", puzzle: "SOK LÚD DISZNÓT GYŐZ" },
    { category: "Közmondás", puzzle: "AJÁNDÉK LÓNAK NE NÉZD A FOGÁT" },
    { category: "Közmondás", puzzle: "NEM MIND ARANY AMI FÉNYLIK" },
    { category: "Közmondás", puzzle: "A SZÜKSÉG TÖRVÉNYT BONT" },
    { category: "Közmondás", puzzle: "AHÁNY HÁZ ANNYI SZOKÁS" },
    { category: "Közmondás", puzzle: "AKI MÁSNAK VERMET ÁS MAGA ESIK BELE" },
    { category: "Közmondás", puzzle: "LASSÚ VÍZ PARTOT MOS" },
    { category: "Közmondás", puzzle: "AZ ALMA NEM ESIK MESSZE A FÁJÁTÓL" },
    { category: "Közmondás", puzzle: "KICSINY A BORS DE ERŐS" },
    { category: "Közmondás", puzzle: "A HAZUG EMBERT HAMARABB UTOLÉRIk MINT A SÁNTA KUTYÁT" },
    { category: "Közmondás", puzzle: "EVÉS KÖZBEN JÖN MEG AZ ÉTVÁGY" },
    { category: "Közmondás", puzzle: "JÓ PAP HOLTIG TANUL" },
    { category: "Közmondás", puzzle: "SOK KICSI SOKRA MEGY" },
    { category: "Közmondás", puzzle: "REND A LELKE MINDENNEK" },
    { category: "Közmondás", puzzle: "A REST KÉTSZER FÁRAD" },
    { category: "Közmondás", puzzle: "MADARAT TOLLÁRÓL EMBERT BARÁTJÁRÓL" },
    { category: "Közmondás", puzzle: "MINDEN CSODA HÁROM NAPIG TART" },
    { category: "Közmondás", puzzle: "A TÜRELEM RÓZSÁT TEREM" },
    { category: "Közmondás", puzzle: "NEM AKARÁSNAK NYÖGÉS A VÉGE" },
    { category: "Közmondás", puzzle: "BAGOLY MONDJA VERÉBNEK HOGY NAGYFEJŰ" },
    { category: "Közmondás", puzzle: "JOBB ADNI MINT KAPNI" },
    { category: "Közmondás", puzzle: "KI A KICSIT NEM BECSÜLI A NAGYOT NEM ÉRDEMLI" },
    { category: "Közmondás", puzzle: "AMELYIK KUTYA UGAT AZ NEM HARAP" },
    { category: "Közmondás", puzzle: "A BAJ NEM JÁR EGYEDÜL" },
    { category: "Közmondás", puzzle: "VAKTYÚK IS TALÁL SZEMET" },
    { category: "Közmondás", puzzle: "KIVÉTEL ERŐSÍTI A SZABÁLYT" },
    { category: "Közmondás", puzzle: "SENKI SEM SZÜLETETT MESTERNEK" },
    { category: "Közmondás", puzzle: "A SZERELEM VAK" },
    { category: "Közmondás", puzzle: "HOLLÓ A HOLLÓNAK NEM VÁJJA KI A SZEMÉT" },
    { category: "Közmondás", puzzle: "MINDEN JÓ HA A VÉGE JÓ" },
    { category: "Közmondás", puzzle: "KÉSŐ BÁNAT EBGONDOLAT" },
    { category: "Közmondás", puzzle: "INÁBA SZÁLLT A BÁTORSÁGA" },
    { category: "Közmondás", puzzle: "SZÉP A KERT DE HIÁNYZIK BELŐLE A KERÍTÉS" },
    { category: "Közmondás", puzzle: "A REMÉNY HAL MEG UTOLJÁRA" },
    { category: "Közmondás", puzzle: "NE FESSÜK AZ ÖRDÖGÖT A FALRA" },
    { category: "Közmondás", puzzle: "TÖBB SZEM TÖBBET LÁT" },
    { category: "Közmondás", puzzle: "EGYSZER VOLT BUDÁN KUTYAVÁSÁR" },
    { category: "Közmondás", puzzle: "ESŐ UTÁN KÖPÖNYEG" },
    { category: "Közmondás", puzzle: "KÁRBA VESZETT BIZALOM" },

    // Kategória: Film & Rendező
    { category: "Film & Rendező", puzzle: "STEVEN SPIELBERG E T A FÖLDÖNKÍVÜLI" },
    { category: "Film & Rendező", puzzle: "JAMES CAMERON TITANIC" },
    { category: "Film & Rendező", puzzle: "GEORGE LUCAS CSILLAGOK HÁBORÚJA" },
    { category: "Film & Rendező", puzzle: "PETER JACKSON A GYŰRŰK URA" },
    { category: "Film & Rendező", puzzle: "CHRISTOPHER NOLAN EREDET" },
    { category: "Film & Rendező", puzzle: "MARTIN SCORSESE NAGYMENŐK" },
    { category: "Film & Rendező", puzzle: "FRANCIS FORD COPPOLA A KERESZTAPA" },
    { category: "Film & Rendező", puzzle: "ALFRED HITCHCOCK PSZICHÓ" },
    { category: "Film & Rendező", puzzle: "RIDLEY SCOTT GLADIÁTOR" },
    { category: "Film & Rendező", puzzle: "SZABÓ ISTVÁN MEPHISTO" },
    { category: "Film & Rendező", puzzle: "TIM BURTON OLLÓKEZŰ EDWARD" },
    { category: "Film & Rendező", puzzle: "DAVID FINCHER HARCOSOK KLUBJA" },
    { category: "Film & Rendező", puzzle: "ROBERT ZEMECKIS VISSZA A JÖVŐBE" },
    { category: "Film & Rendező", puzzle: "LANA WACHOWSKI MÁTRIX" },
    { category: "Film & Rendező", puzzle: "STANLEY KUBRICK RAGYOGÁS" },
    { category: "Film & Rendező", puzzle: "MILOS FORMAN AMADEUS" },
    { category: "Film & Rendező", puzzle: "JANKOVICS MARCELL FEHÉRLÓFIA" },
    { category: "Film & Rendező", puzzle: "MUNDRUCZÓ KORNÉL FEHÉR ISTEN" },
    { category: "Film & Rendező", puzzle: "NEMES JELES LÁSZLÓ SAUL FIA" },
    { category: "Film & Rendező", puzzle: "BEREMÉNYI GÉZA ELDORÁDÓ" },
    { category: "Film & Rendező", puzzle: "DENIS VILLENEUVE DŰNE" },
    { category: "Film & Rendező", puzzle: "WES ANDERSON A GRAND BUDAPEST HOTEL" },
    { category: "Film & Rendező", puzzle: "CHAPLIN A DIKTÁTOR" },
    { category: "Film & Rendező", puzzle: "TAR BÉLA SÁTÁNTANGÓ" },
    { category: "Film & Rendező", puzzle: "FABRI ZOLTÁN A PÁL UTCAI FIÚK" },
    { category: "Film & Rendező", puzzle: "MÉSZÁROS MÁRTA NAPLÓ GYERMEKEIMNEK" },
    { category: "Film & Rendező", puzzle: "JAMES GUNN A GALAXIS ŐRZŐI" },
    { category: "Film & Rendező", puzzle: "BACSÓ PÉTER A TANÚ" },
    { category: "Film & Rendező", puzzle: "SOPSITS ÁRPÁD A WHISKYIS" },
    { category: "Film & Rendező", puzzle: "CLINT EASTWOOD MILLIÓ DOLLÁROS BÉBI" },
    { category: "Film & Rendező", puzzle: "FRANK DARABONT A REMÉNY RABJAI" },

    // Kategória: Irodalom
    { category: "Irodalom", puzzle: "MOLNÁR FERENC A PÁL UTCAI FIÚK" },
    { category: "Irodalom", puzzle: "ARANY JÁNOS TOLDİ" },
    { category: "Irodalom", puzzle: "PETŐFI SÁNDOR JÁNOS VITÉZ" },
    { category: "Irodalom", puzzle: "GÁRDONYI GÉZA EGRI CSILLAGOK" },
    { category: "Irodalom", puzzle: "MADÁCH IMRE AZ EMBER TRAGÉDIÁJA" },
    { category: "Irodalom", puzzle: "MIKSZÁTH KÁLMÁN SZENT PÉTER ESERNYŐJE" },
    { category: "Irodalom", puzzle: "ÖRKÉNY ISTVÁN EGYPERCES NOVELLÁK" },
    { category: "Irodalom", puzzle: "KOSZTOLÁNYI DEZSŐ ÉDES ANNA" },
    { category: "Irodalom", puzzle: "MÓRICZ ZSIGMOND LÉGY JÓ MINDHALÁLIG" },
    { category: "Irodalom", puzzle: "FEKETE ISTVÁN VUK" },
    { category: "Irodalom", puzzle: "WILLIAM SHAKESPEARE RÓMEÓ ÉS JÚLIA" },
    { category: "Irodalom", puzzle: "J K ROWLING HARRY POTTER ÉS A BÖLCSEK KÖVE" },
    { category: "Irodalom", puzzle: "GEORGE ORWELL EZER KILENCSZÁZ NYOLCVAN NÉGY" },
    { category: "Irodalom", puzzle: "J R R TOLKIEN A GYŰRŰK URA" },
    { category: "Irodalom", puzzle: "LEV TOLSZTOJ HÁBORÚ ÉS BÉKE" },
    { category: "Irodalom", puzzle: "REJTŐ JENŐ A PISZKOS FRED A KAPITÁNY" },
    { category: "Irodalom", puzzle: "ANTOINE DE SAINT EXUPÉRY A KIS HERCEG" },
    { category: "Irodalom", puzzle: "FRANZ KAFKA AZ ÁTVÁLTOZÁS" },
    { category: "Irodalom", puzzle: "ALBERT CAMUS A KÖZÖNY" },
    { category: "Irodalom", puzzle: "SZABÓ MAGDA AZ AJTÓ" },
    { category: "Irodalom", puzzle: "KARINTHY FRIGYES ÍGY ÍRTOK TI" },
    { category: "Irodalom", puzzle: "DANIEL DEFOE ROBINSON CRUSOE" },
    { category: "Irodalom", puzzle: "JULES VERNE NYOLCVAN NAP ALATT A FÖLD KÖRÜL" },
    { category: "Irodalom", puzzle: "CERVANTES DON QUIJOTE" },
    { category: "Irodalom", puzzle: "HOMÉROSZ ODÜSSZEIA" },
    { category: "Irodalom", puzzle: "ADY ENDRE VÉRNŐS ASSZONYOK" },
    { category: "Irodalom", puzzle: "BABITS MIHÁLY JÓNÁS KÖNYVE" },
    { category: "Irodalom", puzzle: "JÓZSEF ATTILA TISZTA SZÍVVEL" },
    { category: "Irodalom", puzzle: "KERTÉSZ IMRE SORSTALANSÁG" },
    { category: "Irodalom", puzzle: "VÖRÖSMARTY MIHÁLY CSONGOR ÉS TÜNDE" },
    { category: "Irodalom", puzzle: "GABRIEL GARCÍA MÁRQUEZ SZÁZ ÉV MAGÁNY" },

    // Kategória: Zene
    { category: "Zene", puzzle: "LGT A KICSI A NAGY AZ ARTÚR ÉS AZ INDIÁN" },
    { category: "Zene", puzzle: "MICHAEL JACKSON THRILLER" },
    { category: "Zene", puzzle: "THE BEATLES HEY JUDE" },
    { category: "Zene", puzzle: "NIRVANA SMELLS LIKE TEEN SPIRIT" },
    { category: "Zene", puzzle: "ABBA DANCING QUEEN" },
    { category: "Zene", puzzle: "TANKCSAPDA MENNYORSZÁG TOURIST" },
    { category: "Zene", puzzle: "EDDA MŰVEK KÖR" },
    { category: "Zene", puzzle: "KISPÁL ÉS A BORZ CSILLAG VAGY FEKETE LYUK" },
    { category: "Zene", puzzle: "METALLICA ENTER SANDMAN" },
    { category: "Zene", puzzle: "HALOTT PÉNZ HELLO LÁNYOK" },
    { category: "Zene", puzzle: "BEETHOVEN ÖRÖMÓDA" },
    { category: "Zene", puzzle: "MOZART EGY KIS ÉJI ZENE" },
    { category: "Zene", puzzle: "LISZT FERENC MAGYAR RAPSZÓDIÁK" },
    { category: "Zene", puzzle: "FRANK SINATRA MY WAY" },
    { category: "Zene", puzzle: "ELVIS PRESLEY JAILHOUSE ROCK" },
    { category: "Zene", puzzle: "BOB MARLEY NO WOMAN NO CRY" },
    { category: "Zene", puzzle: "CSEH TAMÁS BUDAPEST" },
    { category: "Zene", puzzle: "REPUBLIC SZÁLLJ EL KISMADÁR" },
    { category: "Zene", puzzle: "ADELE ROLLING IN THE DEEP" },
    { category: "Zene", puzzle: "U2 WITH OR WITHOUT YOU" },
    { category: "Zene", puzzle: "PÉTERFY BORI & LOVE BAND HAJOLJ BELE A HAJAMBA" },
    { category: "Zene", puzzle: "VIVALDI A NÉGY ÉVSZAK" },
    { category: "Zene", puzzle: "JOHANN SEBASTIAN BACH TOCCATA ÉS FÚGA" },
    { category: "Zene", puzzle: "QUIMBY MOST MÚLIK PONTOSAN" },
    { category: "Zene", puzzle: "AC DC HIGHWAY TO HELL" },
    { category: "Zene", puzzle: "LED ZEPPELIN STAIRWAY TO HEAVEN" },
    { category: "Zene", puzzle: "PIRAMIS SZÁLLJ FEL MAGASRA" },
    { category: "Zene", puzzle: "KONCZ ZSUZSA HA ÉN RÓZSA VOLNÉK" },
    { category: "Zene", puzzle: "CARAMEL LÉLEKJEL" },

    // Kategória: Híres Ember
    { category: "Híres Ember", puzzle: "PETŐFI SÁNDOR" },
    { category: "Híres Ember", puzzle: "KOSSUTH LAJOS" },
    { category: "Híres Ember", puzzle: "SZÉCHENYI ISTVÁN" },
    { category: "Híres Ember", puzzle: "SEMMELWEIS IGNÁC" },
    { category: "Híres Ember", puzzle: "PUSKÁS FERENC" },
    { category: "Híres Ember", puzzle: "ERKEL FERENC" },
    { category: "Híres Ember", puzzle: "LEONARDO DA VINCI" },
    { category: "Híres Ember", puzzle: "MARIE CURIE" },
    { category: "Híres Ember", puzzle: "GALILEO GALILEI" },
    { category: "Híres Ember", puzzle: "ISAAC NEWTON" },
    { category: "Híres Ember", puzzle: "NEUMANN JÁNOS" },
    { category: "Híres Ember", puzzle: "BARTÓK BÉLA" },
    { category: "Híres Ember", puzzle: "KODÁLY ZOLTÁN" },
    { category: "Híres Ember", puzzle: "HOSSZÚ KATINKA" },
    { category: "Híres Ember", puzzle: "EGERVÁRI KRISTÓF" },
    { category: "Híres Ember", puzzle: "TERÉZ ANYA" },
    { category: "Híres Ember", puzzle: "NELSON MANDELA" },
    { category: "Híres Ember", puzzle: "MARTIN LUTHER KING" },
    { category: "Híres Ember", puzzle: "MAHATMA GANDHI" },
    { category: "Híres Ember", puzzle: "RUBIK ERNŐ" },
    { category: "Híres Ember", puzzle: "GEORGE WASHINGTON" },
    { category: "Híres Ember", puzzle: "NAPÓLEON BONAPARTE" },
    { category: "Híres Ember", puzzle: "JULIUS CAESAR" },
    { category: "Híres Ember", puzzle: "KLEOPÁTRA" },
    { category: "Híres Ember", puzzle: "CSOKONAI VITÉZ MIHÁLY" },
    { category: "Híres Ember", puzzle: "LATINOVITS ZOLTÁN" },
    { category: "Híres Ember", puzzle: "BODROGI GYULA" },
    { category: "Híres Ember", puzzle: "POLGÁR JUDIT" },
    { category: "Híres Ember", puzzle: "STEVE JOBS" },
    { category: "Híres Ember", puzzle: "BILL GATES" },
    { category: "Híres Ember", puzzle: "ELON MUSK" },

    // Kategória: Földrajz
    { category: "Földrajz", puzzle: "A DUNA EURÓPA MÁSODIK LEGHOSSZABB FOLYÓJA" },
    { category: "Földrajz", puzzle: "BUDAPEST MAGYARORSZÁG FŐVÁROSA" },
    { category: "Földrajz", puzzle: "MOUNT EVEREST A VILÁG LEGMAGASABB HEGYE" },
    { category: "Földrajz", puzzle: "AZ AMAZONAS ESŐERDŐ" },
    { category: "Földrajz", puzzle: "A SZAHARA A LEGNAGYOBB FORRÓ SIVATAG" },
    { category: "Földrajz", puzzle: "A KÍNAI NAGY FAL" },
    { category: "Földrajz", puzzle: "A NIAGARA VÍZESÉS" },
    { category: "Földrajz", puzzle: "AZ EGRI VÁR" },
    { category: "Földrajz", puzzle: "A BALATON KÖZÉP EURÓPA LEGNAGYOBB TAVA" },
    { category: "Földrajz", puzzle: "A PÁRIZSI EIFFEL TORONY" },
    { category: "Földrajz", puzzle: "A RÓMAI COLOSSEUM" },
    { category: "Földrajz", puzzle: "A GÍZAI NAGY PIRAMIS" },
    { category: "Földrajz", puzzle: "A CSENDES ÓCEÁN" },
    { category: "Földrajz", puzzle: "MADAGASZKÁR SZIGETE" },
    { category: "Földrajz", puzzle: "A NAGY KORALLZÁTONY AUSZTRÁLIÁBAN" },
    { category: "Földrajz", puzzle: "TOKIO JAPÁN FŐVÁROSA" },
    { category: "Földrajz", puzzle: "A DÉLI SARK" },
    { category: "Földrajz", puzzle: "A KÁRPÁTOK VONULATA" },
    { category: "Földrajz", puzzle: "A TISZA FOLYÓ" },
    { category: "Földrajz", puzzle: "A FÖLDKÖZI TENGER" },
    { category: "Földrajz", puzzle: "A SZIBÉRIAI TAJGA" },
    { category: "Földrajz", puzzle: "A GRAND CANYON AZ EGYESÜLT ÁLLAMOKBAN" },
    { category: "Földrajz", puzzle: "AZ INDIAI ÓCEÁN" },
    { category: "Földrajz", puzzle: "A VIKTÓRIA VÍZESÉS" },
    { category: "Földrajz", puzzle: "A SZENTENDREI SZIGET" },
    { category: "Földrajz", puzzle: "AGGTELEKI CSEPPKŐBARLANG" },
    { category: "Földrajz", puzzle: "A VELENCEI KARNEVÁL" },
    { category: "Földrajz", puzzle: "A SZUEZI CSATORNA" },
    { category: "Földrajz", puzzle: "AZ ANDOK HEGYSÉG" },
    { category: "Földrajz", puzzle: "MOSZKVA OROSZORSZÁG FŐVÁROSA" },

    // Kategória: Történelem
    { category: "Történelem", puzzle: "A MAGYAR HONFOGLALÁS" },
    { category: "Történelem", puzzle: "AZ 1848-AS FORRADALOM ÉS SZABADSÁGHARC" },
    { category: "Történelem", puzzle: "A RÓMAI BIRODALOM BUKÁSA" },
    { category: "Történelem", puzzle: "A BERLINI FAL LEOMBLASA" },
    { category: "Történelem", puzzle: "A MUHACSI CSATA" },
    { category: "Történelem", puzzle: "AZ ELSŐ VILÁGHÁBORÚ" },
    { category: "Történelem", puzzle: "A KÖZÉPKOR" },
    { category: "Törtélelem", puzzle: "A REFORMÁCIÓ" },
    { category: "Történelem", puzzle: "AZ AMERIKAI FÜGGETLENSÉGI HÁBORÚ" },
    { category: "Történelem", puzzle: "A FRANCIA FORRADALOM" },
    { category: "Történelem", puzzle: "A TATÁRJÁRÁS" },
    { category: "Történelem", puzzle: "A TRIANONI BÉKESZERZŐDÉS" },
    { category: "Történelem", puzzle: "A HIDEGHÁBORÚ" },
    { category: "Történelem", puzzle: "A VIKING KOR" },
    { category: "Történelem", puzzle: "AZ ÓKORI EGYIPTOM" },
    { category: "Történelem", puzzle: "A VASKOR" },
    { category: "Történelem", puzzle: "A KIEGYEZÉS" },
    { category: "Történelem", puzzle: "A RÁKÓCZI SZABADSÁGHARC" },
    { category: "Történelem", puzzle: "A NÁNDORFEHÉRVÁRI DIADAL" },
    { category: "Történelem", puzzle: "AZ ARANYBULLA" },
    { category: "Történelem", puzzle: "A HOLOKAUSZT" },
    { category: "Történelem", puzzle: "A SZOVJETUNIÓ FELBOMLÁSA" },
    { category: "Történelem", puzzle: "A HOLDFÖLDRE SZÁLLÁS" },
    { category: "Történelem", puzzle: "A RENESZÁNSZ KORA" },
    { category: "Történelem", puzzle: "AZ APOLLÓ TIZENEGY KÜLDETÉS" },

    // Kategória: Tudomány
    { category: "Tudomány", puzzle: "A DNS KETTŐS SPIRÁL SZERKEZETE" },
    { category: "Tudomány", puzzle: "ISAAC NEWTON GRAVITÁCIÓS TÖRVÉNYE" },
    { category: "Tudomány", puzzle: "A FÉNY SEBESSÉGE VÁKUUMBAN" },
    { category: "Tudomány", puzzle: "SZENT GYÖRGYI ALBERT ÉS A C VITAMIN" },
    { category: "Tudomány", puzzle: "CHARLES DARWIN EVOLÚCIÓELMÉLETE" },
    { category: "Tudomány", puzzle: "A PITAGORASZ TÉTEL" },
    { category: "Tudomány", puzzle: "A VÍZ FORRÁSPONTJA" },
    { category: "Tudomány", puzzle: "A PERIÓDUSOS RENDSZER" },
    { category: "Tudomány", puzzle: "FEKETE LYUK A TÉRIDŐ GÖRBÜLETE" },
    { category: "Tudomány", puzzle: "A FOTOSZINTÉZIS FOLYAMATA" },
    { category: "Tudomány", puzzle: "KOPERNIKUSZ HELIOCENTRIKUS VILÁGKÉPE" },
    { category: "Tudomány", puzzle: "A HANGTERJEDÉS SEBESSÉGE" },
    { category: "Tudomány", puzzle: "AZ ATOMMAG HASADÁSA" },
    { category: "Tudomány", puzzle: "A NAPELEMEK MŰKÖDÉSI ELVE" },
    { category: "Tudomány", puzzle: "GREGOR MENDEL ÉS A GENETIKA" },
    { category: "Tudomány", puzzle: "A NAGY BUMM ELMÉLETE" },
    { category: "Tudomány", puzzle: "ALEXANDER FLEMING ÉS A PENICILLIN" },
    { category: "Tudomány", puzzle: "A MÁGNESES MEZŐ" },
    { category: "Tudomány", puzzle: "A HORMONRENDSZER MŰKÖDÉSE" },
    { category: "Tudomány", puzzle: "AZ INTERNET FELTALÁLÁSA" },
    { category: "Tudomány", puzzle: "ARCHIMÉDESZ TÖRVÉNYE" },
    { category: "Tudomány", puzzle: "A LÉZER TECHNOLÓGIA" },
    { category: "Tudomány", puzzle: "AZ EMBERI GENOM PROJEKT" },
    { category: "Tudomány", puzzle: "A KVANTUMMECHANIKA" },

    // Kategória: Étel & Ital
    { category: "Étel & Ital", puzzle: "GULYÁSLEVES CSIPETKÉVEL" },
    { category: "Étel & Ital", puzzle: "TÖLTÖTT KÁPOSZTA TEJFÖLLEL" },
    { category: "Étel & Ital", puzzle: "PIZZA MARGHERITA" },
    { category: "Étel & Ital", puzzle: "ESZPRESSZÓ KÁVÉ" },
    { category: "Étel & Ital", puzzle: "TOKAJI ASZÚ" },
    { category: "Étel & Ital", puzzle: "HALÁSZLÉ GYUFA TÉSZTÁVAL" },
    { category: "Étel & Ital", puzzle: "CSIRKEPAPRIKÁS NOKEDLIVEL" },
    { category: "Étel & Ital", puzzle: "RÁNTOTT SAJT TARTÁRMÁRTÁSSAL" },
    { category: "Étel & Ital", puzzle: "SOMÓI GALUSKA" },
    { category: "Étel & Ital", puzzle: "DOBOSTORTA" },
    { category: "Étel & Ital", puzzle: "KÜRTŐSKALÁCS" },
    { category: "Étel & Ital", puzzle: "PALACSINTA KAKAÓVAL" },
    { category: "Étel & Ital", puzzle: "LÁNGOS SAJTTAL ÉS TEJFÖLLEL" },
    { category: "Étel & Ital", puzzle: "LECSÓ KOLBÁSSZAL" },
    { category: "Étel & Ital", puzzle: "SPAGETTI BOLOGNESE" },
    { category: "Étel & Ital", puzzle: "HAMBURGER HASÁBBURGONYÁVAL" },
    { category: "Étel & Ital", puzzle: "PÖRKÖLT TARHONYÁVAL" },
    { category: "Étel & Ital", puzzle: "EGRI BIKAVÉR" },
    { category: "Étel & Ital", puzzle: "FRÖCCS" },
    { category: "Étel & Ital", puzzle: "TÚRÓGOMBÓC" },
    { category: "Étel & Ital", puzzle: "MÁKOS GUBA" },
    { category: "Étel & Ital", puzzle: "SZUSI ÉS SZASIMI" },
    { category: "Étel & Ital", puzzle: "GÖRÖG SALÁTA" },
    { category: "Étel & Ital", puzzle: "GYROS PITÁBAN" },
    { category: "Étel & Ital", puzzle: "SZILVÁS GOMBÓC" },
    { category: "Étel & Ital", puzzle: "BEJGLI" },
    { category: "Étel & Ital", puzzle: "PÁLINKA" },
    { category: "Étel & Ital", puzzle: "ZSERBÓ SZELET" },

    // Kategória: Élőlény
    { category: "Élőlény", puzzle: "KÉK BÁLNA A LEGNAGYOBB EMLŐS" },
    { category: "Élőlény", puzzle: "NAGY FEHÉR CÁPA" },
    { category: "Élőlény", puzzle: "GÍMSZARVAS" },
    { category: "Élőlény", puzzle: "FEHÉR GÓLYA" },
    { category: "Élőlény", puzzle: "MAGYAR VIZSLA" },
    { category: "Élőlény", puzzle: "AFRIKAI OROSZLÁN" },
    { category: "Élőlény", puzzle: "PULI KUTYA" },
    { category: "Élőlény", puzzle: "SZIBÉRIAI TIGRIS" },
    { category: "Élőlény", puzzle: "JEGESMEDVE" },
    { category: "Élőlény", puzzle: "ÓRIÁSPANDA" },
    { category: "Élőlény", puzzle: "KOLIBRI" },
    { category: "Élőlény", puzzle: "BARNA MEDVE" },
    { category: "Élőlény", puzzle: "VÖRÖS RÓKA" },
    { category: "Élőlény", puzzle: "HÁZI MACSKA" },
    { category: "Élőlény", puzzle: "ZSIRÁF" },
    { category: "Élőlény", puzzle: "CSÁSZÁRPINGVIN" },
    { category: "Élőlény", puzzle: "TARANTULA PÓK" },
    { category: "Élőlény", puzzle: "KAMÉLEON" },
    { category: "Élőlény", puzzle: "PÁVA" },
    { category: "Élőlény", puzzle: "LAJHÁR" },
    { category: "Élőlény", puzzle: "NÍLUSI KROKODIL" },
    { category: "Élőlény", puzzle: "KOMÓDÓI VARÁNUSZ" },
    { category: "Élőlény", puzzle: "EURÁZSIAI HÓD" },
    { category: "Élőlény", puzzle: "SZÜRKE MARHA" },
    { category: "Élőlény", puzzle: "HÓBAGOLY" },

    // Kategória: Növény
    { category: "Növény", puzzle: "TÖLGYFA" },
    { category: "Növény", puzzle: "NAPRAFORGÓ" },
    { category: "Növény", puzzle: "RÓZSA" },
    { category: "Növény", puzzle: "TULIPÁN" },
    { category: "Növény", puzzle: "AKÁCFA" },
    { category: "Növény", puzzle: "HÓVIRÁG" },
    { category: "Növény", puzzle: "KAMILLA" },
    { category: "Növény", puzzle: "LEVENDULA" },
    { category: "Növény", puzzle: "PITYPANG" },
    { category: "Növény", puzzle: "LEÁNDER" },
    { category: "Növény", puzzle: "BÚZA" },
    { category: "Növény", puzzle: "KUKORICA" },
    { category: "Növény", puzzle: "BAOBAB FA" },
    { category: "Növény", puzzle: "FENYŐFA" },
    { category: "Növény", puzzle: "GOMBA" },
    { category: "Növény", puzzle: "PÁFRÁNY" },
    { category: "Növény", puzzle: "ORGONA" },
    { category: "Növény", puzzle: "SZŐLŐTŐKE" },
    { category: "Növény", puzzle: "PAPRIKA" },
    { category: "Növény", puzzle: "PARADICSOM" },
    { category: "Növény", puzzle: "GÍNKGO BILOBA" },
    { category: "Növény", puzzle: "VÉNUSZ LÉGYCSAPÓJA" },
    { category: "Növény", puzzle: "KAKTUSZ" },
    { category: "Növény", puzzle: "TAVIRÓZSA" },
    { category: "Növény", puzzle: "MOHA" },

    // Kategória: Tárgy
    { category: "Tárgy", puzzle: "OKOSTELEFON TÖLTŐKÁBEL" },
    { category: "Tárgy", puzzle: "ROZSDAMENTES ACÉL EDÉNYKÉSZLET" },
    { category: "Tárgy", puzzle: "BICIKLIPUMPA" },
    { category: "Tárgy", puzzle: "GOLYÓSTOLL" },
    { category: "Tárgy", puzzle: "ASZTALI LÁMPA" },
    { category: "Tárgy", puzzle: "KÖNYVESPOLC" },
    { category: "Tárgy", puzzle: "FÉNYKÉPEZŐGÉP" },
    { category: "Tárgy", puzzle: "DUGÓHÚZÓ" },
    { category: "Tárgy", puzzle: "ESERNYŐ" },
    { category: "Tárgy", puzzle: "HAJSZÁRÍTÓ" },
    { category: "Tárgy", puzzle: "MIKROHULLÁMÚ SÜTŐ" },
    { category: "Tárgy", puzzle: "PORSZÍVÓ" },
    { category: "Tárgy", puzzle: "ÍRÓASZTAL" },
    { category: "Tárgy", puzzle: "KARÓRA" },
    { category: "Tárgy", puzzle: "TÁVIRÁNYÍTÓ" },
    { category: "Tárgy", puzzle: "FOGKEFE" },
    { category: "Tárgy", puzzle: "LAPTOP TÁSKA" },
    { category: "Tárgy", puzzle: "KÁVÉFŐZŐ" },
    { category: "Tárgy", puzzle: "VÍZFORRALÓ" },
    { category: "Tárgy", puzzle: "FALINAPTÁR" },
    { category: "Tárgy", puzzle: "SZEMÜVEGTOK" },
    { category: "Tárgy", puzzle: "GEMKAPOCS" },
    { category: "Tárgy", puzzle: "VARRÓTŰ" },
    { category: "Tárgy", puzzle: "CSAVARHÚZÓ KÉSZLET" },
    { category: "Tárgy", puzzle: "KULCSCSOMÓ" },

    // Kategória: Sport
    { category: "Sport", puzzle: "OLIMPIAI JÁTÉKOK" },
    { category: "Sport", puzzle: "LABDARÚGÓ VILÁGBAJNOKSÁG" },
    { category: "Sport", puzzle: "FORMULA 1 MAGYAR NAGYDÍJ" },
    { category: "Sport", puzzle: "KOVÁCS KATALIN OLIMPIAI BAJNOK KAJAKOZÓ" },
    { category: "Sport", puzzle: "TOUR DE FRANCE KERÉKPÁRVERSENY" },
    { category: "Sport", puzzle: "WIMBLEDONI TENISZBAJNOKSÁG" },
    { category: "Sport", puzzle: "SZILÁGYI ÁRON HÁROMSZOROS OLIMPIAI BAJNOK VÍVÓ" },
    { category: "Sport", puzzle: "KOSÁRLABDA" },
    { category: "Sport", puzzle: "VÍZILABDA" },
    { category: "Sport", puzzle: "ATLÉTIKA" },
    { category: "Sport", puzzle: "ÚSZÁS" },
    { category: "Sport", puzzle: "KÉZILABDA" },
    { category: "Sport", puzzle: "JEGKORONG" },
    { category: "Sport", puzzle: "A NEMZETI BAJNOKSÁG" },
    { category: "Sport", puzzle: "ARANYCSAPAT" },
    { category: "Sport", puzzle: "SUPER BOWL" },
    { category: "Sport", puzzle: "BAJNOKOK LIGÁJA" },
    { category: "Sport", puzzle: "MICHAEL JORDAN" },
    { category: "Sport", puzzle: "ROGER FEDERER" },
    { category: "Sport", puzzle: "USAIN BOLT" },
    { category: "Sport", puzzle: "MICHAEL SCHUMACHER" },
    { category: "Sport", puzzle: "LIONEL MESSI" },
    { category: "Sport", puzzle: "CRISTIANO RONALDO" },
    { category: "Sport", puzzle: "LEBRON JAMES" },
    { category: "Sport", puzzle: "MICHAEL PHELPS" },
    { category: "Sport", puzzle: "GYARMATI DEZSŐ" },
    { category: "Sport", puzzle: "DARNYI TAMÁS" },

    // Kategória: Márkanév
    { category: "Márkanév", puzzle: "COCA COLA" },
    { category: "Márkanév", puzzle: "LEGO" },
    { category: "Márkanév", puzzle: "PICK SZEGED" },
    { category: "Márkanév", puzzle: "AUDI" },
    { category: "Márkanév", puzzle: "NIKE" },
    { category: "Márkanév", puzzle: "ADIDAS" },
    { category: "Márkanév", puzzle: "APPLE" },
    { category: "Márkanév", puzzle: "SAMSUNG" },
    { category: "Márkanév", puzzle: "GOOGLE" },
    { category: "Márkanév", puzzle: "FACEBOOK" },
    { category: "Márkanév", puzzle: "MCDONALDS" },
    { category: "Márkanév", puzzle: "IKEA" },
    { category: "Márkanév", puzzle: "ZARA" },
    { category: "Márkanév", puzzle: "PÖTTYÖS TÚRÓ RUDI" },
    { category: "Márkanév", puzzle: "HERENDI PORCELÁN" },
    { category: "Márkanév", puzzle: "GYŐRI KEKSZ" },
    { category: "Márkanév", puzzle: "TESCO" },
    { category: "Márkanév", puzzle: "LIDL" },
    { category: "Márkanév", puzzle: "SPAR" },
    { category: "Márkanév", puzzle: "TOYOTA" },
    { category: "Márkanév", puzzle: "BMW" },
    { category: "Márkanév", puzzle: "NETFLIX" },
    { category: "Márkanév", puzzle: "SPOTIFY" },
    { category: "Márkanév", puzzle: "FERRARI" },
    { category: "Márkanév", puzzle: "SONY PLAYSTATION" },

    // Kategória: Mindennapi élet
    { category: "Mindennapi élet", puzzle: "HOLNAP REGGEL KORÁN KELL KELNEM" },
    { category: "Mindennapi élet", puzzle: "ELNÉZÉST MERRE VAN A LEGÖZELEBBI PATIKA" },
    { category: "Mindennapi élet", puzzle: "ELFOGYOTT A TEJ A HŰTŐBŐL" },
    { category: "Mindennapi élet", puzzle: "LEMERÜLT A TELEFONOM" },
    { category: "Mindennapi élet", puzzle: "BEVÁSÁRLÓLISTÁT ÍROK" },
    { category: "Mindennapi élet", puzzle: "ELKÉSEK A MUNKÁBÓL" },
    { category: "Mindennapi élet", puzzle: "NINCS ITTHON KENYÉR" },
    { category: "Mindennapi élet", puzzle: "VIGYÉL ESERNYŐT MERT ESNI FOG" },
    { category: "Mindennapi élet", puzzle: "MIT KÉRSZ EBÉDRE" },
    { category: "Mindennapi élet", puzzle: "ELFELEJTETTEM A JELSZAVAM" },
    { category: "Mindennapi élet", puzzle: "KAPCSOLD BE A TELEVÍZIÓT" },
    { category: "Mindennapi élet", puzzle: "LE KELL VINNI A SZEMETET" },
    { category: "Mindennapi élet", puzzle: "NINCS INTERNETKAPCSOLAT" },
    { category: "Mindennapi élet", puzzle: "HÁNY ÓRA VAN" },
    { category: "Mindennapi élet", puzzle: "FELHÍVLAK KÉSŐBB" },
    { category: "Mindennapi élet", puzzle: "BOLDOG SZÜLETÉSNAPOT KÍVÁNOK" },
    { category: "Mindennapi élet", puzzle: "NAGYON JÓL ÉREZTEM MAGAM" },
    { category: "Mindennapi élet", puzzle: "EGY KÁVÉT KÉREK SZÉPEN" },
    { category: "Mindennapi élet", puzzle: "HOL TALÁLOM A MOSDÓT" },
    { category: "Mindennapi élet", puzzle: "NEM MŰKÖDIK A BANKKÁRTYA TERMINÁL" },
    { category: "Mindennapi élet", puzzle: "KÜLDD ÁT EMAILBEN LÉGYSZÍVES" },
    { category: "Mindennapi élet", puzzle: "BE KELL FIZETNI A SZÁMLÁKAT" },
    { category: "Mindennapi élet", puzzle: "FORGALMI DUGÓBA KERÜLTEM" },
    { category: "Mindennapi élet", puzzle: "MENNYI AZ IDŐ" },
    { category: "Mindennapi élet", puzzle: "JÓ ÉTVÁGYAT" },
    { category: "Mindennapi élet", puzzle: "SOK SIKERT A VIZSGÁHOZ" },

    // Kategória: Fogalom
    { category: "Fogalom", puzzle: "A SZABADSÁG ÉS A SZERELEM" },
    { category: "Fogalom", puzzle: "DEMOKRÁCIA" },
    { category: "Fogalom", puzzle: "EMBERI JOGOK" },
    { category: "Fogalom", puzzle: "BARÁTSÁG" },
    { category: "Fogalom", puzzle: "KÉPZELET" },
    { category: "Fogalom", puzzle: "KREATIVITÁS" },
    { category: "Fogalom", puzzle: "BÖLCSESSÉG" },
    { category: "Fogalom", puzzle: "IGAZSÁG" },
    { category: "Fogalom", puzzle: "HŰSÉG" },
    { category: "Fogalom", puzzle: "TISZTELET" },
    { category: "Fogalom", puzzle: "INFLÁCIÓ" },
    { category: "Fogalom", puzzle: "GLOBÁLIS FELMELEGEDÉS" },
    { category: "Fogalom", puzzle: "KÖRNYEZETVÉDELEM" },
    { category: "Fogalom", puzzle: "VÉLETLEN" },
    { category: "Fogalom", puzzle: "SORS" },
    { category: "Fogalom", puzzle: "KULTÚRA" },
    { category: "Fogalom", puzzle: "CIVILIZÁCIÓ" },
    { category: "Fogalom", puzzle: "A HUMOR ÉS A NEVETÉS" },
    { category: "Fogalom", puzzle: "AZ ÁLMOK ÉS A VALÓSÁG" },
    { category: "Fogalom", puzzle: "A MÚLT ÉS A JÖVŐ" },

    // Kategória: Foglalkozás
    { category: "Foglalkozás", puzzle: "TŰZOLTÓ" },
    { category: "Foglalkozás", puzzle: "ORVOS" },
    { category: "Foglalkozás", puzzle: "TANÁR" },
    { category: "Foglalkozás", puzzle: "RENDŐR" },
    { category: "Foglalkozás", puzzle: "PROGRAMOZÓ" },
    { category: "Foglalkozás", puzzle: "PÉK" },
    { category: "Foglalkozás", puzzle: "SZAKÁCS" },
    { category: "Foglalkozás", puzzle: "FODRÁSZ" },
    { category: "Foglalkozás", puzzle: "ÜGYVÉD" },
    { category: "Foglalkozás", puzzle: "ÉPÍTÉSZMÉRNÖK" },
    { category: "Foglalkozás", puzzle: "ÁLLATORVOS" },
    { category: "Foglalkozás", puzzle: "POSTÁS" },
    { category: "Foglalkozás", puzzle: "SZÍNÉSZ" },
    { category: "Foglalkozás", puzzle: "ZENÉSZ" },
    { category: "Foglalkozás", puzzle: "FESTŐMŰVÉSZ" },
    { category: "Foglalkozás", puzzle: "ÚJSÁGÍRÓ" },
    { category: "Foglalkozás", puzzle: "PILÓTA" },
    { category: "Foglalkozás", puzzle: "ASZTALOS" },
    { category: "Foglalkozás", puzzle: "VILLANYSZERELŐ" },
    { category: "Foglalkozás", puzzle: "KÖNYVELŐ" },
    { category: "Foglalkozás", puzzle: "TUDÓS" },
    { category: "Foglalkozás", puzzle: "GRAFIKUS" },
    { category: "Foglalkozás", puzzle: "MARKETING MENEDZSER" },
    { category: "Foglalkozás", puzzle: "BANKÁR" },
    { category: "Foglalkozás", puzzle: "PSZICHOLÓGUS" },

    // Kategória: Csillagászat
    { category: "Csillagászat", puzzle: "TEJÚTRENDSZER" },
    { category: "Csillagászat", puzzle: "NAGY MEDVE CSILLAGKÉP" },
    { category: "Csillagászat", puzzle: "A HOLD FOGYATKOZÁSA" },
    { category: "Csillagászat", puzzle: "A NAPRENDSZER BOLYGÓI" },
    { category: "Csillagászat", puzzle: "HALLEY ÜSTÖKÖS" },
    { category: "Csillagászat", puzzle: "HUBBLE ŰRTÁVCSŐ" },
    { category: "Csillagászat", puzzle: "ANDROMÉDA GALAXIS" },
    { category: "Csillagászat", puzzle: "A JUPITER NAGY VÖRÖS FOLTJA" },
    { category: "Csillagászat", puzzle: "A SZATURNUSZ GYŰRŰI" },
    { category: "Csillagászat", puzzle: "METEORRAJ" },
    { category: "Csillagászat", puzzle: "SARKIFÉNY" },
    { category: "Csillagászat", puzzle: "CSILLAGHULLÁS" },
    { category: "Csillagászat", puzzle: "A MARS A VÖRÖS BOLYGÓ" },
    { category: "Csillagászat", puzzle: "NEMZETKÖZI ŰRÁLLOMÁS" },
    { category: "Csillagászat", puzzle: "VÉNUSZ AZ ESTHAJNALCSILLAG" },
    { category: "Csillagászat", puzzle: "NAPFOGYATKOZÁS" },
    { category: "Csillagászat", puzzle: "TÖRPEBOLYGÓ" },
    { category: "Csillagászat", puzzle: "A FÖLD KERINGÉSE A NAP KÖRÜL" },
    { category: "Csillagászat", puzzle: "CSILLAGKÖD" },
    { category: "Csillagászat", puzzle: "PULZÁR" },

    // Vegyes kategóriák a teljességért (további ~500)
    { category: "Étel & Ital", puzzle: "SZALONNACUKOR" },
    { category: "Sport", puzzle: "EURÓPA LIGA" },
    { category: "Irodalom", puzzle: "ERICH KÄSTNER A KÉT LOTTI" },
    { category: "Híres Ember", puzzle: "BUD SPENCER" },
    { category: "Film", puzzle: "A KARIB TENGER KALÓZAI" },
    { category: "Földrajz", puzzle: "A HOLT TENGER" },
    { category: "Tudomány", puzzle: "RELATIVITÁS" },
    { category: "Zene", puzzle: "KFT BALATONI NYÁR" },
    { category: "Közmondás", puzzle: "A BECSÜLET DRÁGÁBB AZ ARANYNÁL" },
    { category: "Tárgy", puzzle: "MOBILTELEFON" },
    { category: "Élőlény", puzzle: "HÁZI MÉH" },
    { category: "Mindennapi élet", puzzle: "FELADOM A POSTÁN" },
    { category: "Márkanév", puzzle: "Zsolnay Porcelán" },
    { category: "Történelem", puzzle: "A HUSZÁR" },
    { category: "Sport", puzzle: "BUDAPEST HONVÉD" },
    { category: "Film & Rendező", puzzle: "GAUDER ÁRON KOJOT NÉGY LELKE" },
    { category: "Zene", puzzle: "BRÓDY JÁNOS FILLÉRES EMLÉKEIM" },
    { category: "Foglalkozás", puzzle: "REPÜLŐGÉP SZERELŐ" },
    { category: "Közmondás", puzzle: "AKI KÍVÁNCSI HAMAR MEGSÖREGszik" },
    { category: "Tárgy", puzzle: "KULACS" },
    { category: "Étel & Ital", puzzle: "TÚRÓS CSUSZA" },
    { category: "Híres Ember", puzzle: "ZSÓFIA KIRÁLYNÉ" },
    { category: "Földrajz", puzzle: "A Vatikánváros" },
    { category: "Tudomány", puzzle: "LEPKEHATÁS" },
    { category: "Irodalom", puzzle: "DICKENS KARÁCSONYI ÉNEK" },
    { category: "Sport", puzzle: "SZOBOSZLAI DOMINIK" },
    { category: "Márkanév", puzzle: "UNIVER" },
    { category: "Film", puzzle: "INDUL A BAKTERHÁZ" },
    { category: "Élőlény", puzzle: "EURÁZSIAI HIÚZ" },
    { category: "Mindennapi élet", puzzle: "A SZOMSZÉD FÜVE MINDIG ZÖLDEBB" },
    { category: "Zene", puzzle: "THE ROLLING STONES PAINT IT BLACK" },
    { category: "Történelem", puzzle: "A LOVAGKOR" },
    { category: "Csillagászat", puzzle: "FEHÉR TÖRPE" },
    { category: "Tárgy", puzzle: "KÖRÖMLAKK" },
    { category: "Étel & Ital", puzzle: "SZÓDAVÍZ" },
    { category: "Híres Ember", puzzle: "ERZSÉBET KIRÁLYNÉ" },
    { category: "Földrajz", puzzle: "HORTBÁGYI NEMZETI PARK" },
    { category: "Sport", puzzle: "FERENCVÁROSI TORNA CLUB" },
    { category: "Film", puzzle: "CSINIBABA" },
    { category: "Közmondás", puzzle: "JOBB EGY VERÉB MINT TÍZ TÚZOK" },
    { category: "Irodalom", puzzle: "MARK TWAIN TOM SAWYER KALANDJAI" },
    { category: "Zene", puzzle: "RÚZSA MAGDI GABRIEL" },
    { category: "Tudomány", puzzle: "AZ ŐSSEJT KUTATÁS" },
    { category: "Márkanév", puzzle: "RICHTER GEDEON" },
    { category: "Élőlény", puzzle: "ARANYHAL" },
    { category: "Mindennapi élet", puzzle: "KIFOGYOTT A NYOMTATÓBÓL A PAPÍR" },
    { category: "Tárgy", puzzle: "FALIÓRA" },
    { category: "Étel & Ital", puzzle: "KRÉMES" },
    { category: "Film", puzzle: "MACSKAFOGÓ" },
    { category: "Sport", puzzle: "TÉLI OLIMPIA" },
    { category: "Híres Ember", puzzle: "SZÉLL KÁLMÁN" },
    { category: "Földrajz", puzzle: "BERLIN" },
    { category: "Történelem", puzzle: "A REFORMKOR" },
    { category: "Zene", puzzle: "HUNGÁRIA CSILLAGOK HÁBORÚJA" },
    { category: "Közmondás", puzzle: "A MUNKA NEMESÍT" },
    { category: "Irodalom", puzzle: "NEMES NAGY ÁGNES A LÁTHATATLAN RÉT" },
    { category: "Tudomány", puzzle: "A MESTERSÉGES INTELLIGENCIA" },
    { category: "Márkanév", puzzle: "MOL" },
    { category: "Élőlény", puzzle: "TENGERI CSILLAG" },
    { category: "Mindennapi élet", puzzle: "NEM TALÁLOM A SZEMÜVEGEMET" },
    { category: "Tárgy", puzzle: "KONZERVNYITÓ" },
    { category: "Étel & Ital", puzzle: "HAGYMÁS ROSTÉLYOS" },
    { category: "Film", puzzle: "A TENKES KAPITÁNYA" },
    { category: "Sport", puzzle: "MAGYAR KUPA" },
    { category: "Híres Ember", puzzle: "JÁSZAI MARI" },
    { category: "Földrajz", puzzle: "AZ ALPOK" },
    { category: "Történelem", puzzle: "A BASTILLE BEVÉTELE" },
    { category: "Zene", puzzle: "KORÁL MARADJ VELEM" },
    { category: "Közmondás", puzzle: "AZ IDŐ PÉNZ" },
    { category: "Irodalom", puzzle: "FEKETE ISTVÁN TÉLI BEREK" },
    { category: "Tudomány", puzzle: "A KLÓNOZÁS ETIKAI KÉRDÉSEI" },
    { category: "Márkanév", puzzle: "OTP BANK" },
    { category: "Élőlény", puzzle: "HÁZI SERTÉS" },
    { category: "Mindennapi élet", puzzle: "KÉRLEK ADD IDE A SÓT" },
    { category: "Tárgy", puzzle: "HÁTIZSÁK" },
    { category: "Étel & Ital", puzzle: "VADAS MARHA ZSEMLEGOMBÓCCAL" },
    { category: "Film", puzzle: "SOSE HALUNK MEG" },
    { category: "Sport", puzzle: "ÚJPESTI TORNA EGYLET" },
    { category: "Híres Ember", puzzle: "GÁBOR ZSAZSA" },
    { category: "Földrajz", puzzle: "A KÉKESTETŐ" },
    { category: "Történelem", puzzle: "A SZPARTAKUSZ FELKELÉS" },
    { category: "Zene", puzzle: "BOGNÁR SZILVIA INDULJ EL EGY ÚTON" },
    { category: "Közmondás", puzzle: "A STÍLUS MAGA AZ EMBER" },
    { category: "Irodalom", puzzle: "SZERB ANTAL A PENDRAGON LEGENDA" },
    { category: "Tudomány", puzzle: "NANOTECHNOLÓGIA" },
    { category: "Márkanév", puzzle: "ZWACK UNICUM" },
    { category: "Élőlény", puzzle: "VÖRÖS PANDA" },
    { category: "Mindennapi élet", puzzle: "BEZÁRTAM AZ AJTÓT" },
    { category: "Tárgy", puzzle: "CERUZAHEGYEZŐ" },
    { category: "Étel & Ital", puzzle: "PAPRIKÁS KRUMPLI" },
    { category: "Film", puzzle: "A GYŰRŰK URA A KIRÁLY VISSZATÉR" },
    { category: "Sport", puzzle: "PARALIMPIA" },
    { category: "Híres Ember", puzzle: "TÖRŐCSIK MARI" },
    { category: "Földrajz", puzzle: "A SZENT ANNA TÓ" },
    { category: "Történelem", puzzle: "AZ ÓKORI GÖRÖGORSZÁG" },
    { category: "Zene", puzzle: "BILLY JOEL PIANO MAN" },
    { category: "Közmondás", puzzle: "A JÓBÓL IS MEGÁRT A SOK" },
    { category: "Irodalom", puzzle: "RUDYARD KIPLING A DZSUNGEL KÖNYVE" },
    { category: "Tudomány", puzzle: "A GENETIKAILAG MÓDOSÍTOTT SZERVEZETEK" },
    { category: "Márkanév", puzzle: "HELL ENERGY" },
    { category: "Élőlény", puzzle: "FEKETE PÁRDUC" },
    { category: "Mindennapi élet", puzzle: "NEM JÖN A BUSZ" },
    { category: "Tárgy", puzzle: "OLLÓ" },
    { category: "Étel & Ital", puzzle: "BRASSÓI APRÓPECSENYE" },
    { category: "Film", puzzle: "AZ OROSZLÁNKIRÁLY" },
    { category: "Sport", puzzle: "TÍZPRÓBA" },
    { category: "Híres Ember", puzzle: "HAUMANN PÉTER" },
    { category: "Földrajz", puzzle: "VELENCEI TÓ" },
    { category: "Történelem", puzzle: "A KÖNYVNYOMTATÁS FELTALÁLÁSA" },
    { category: "Zene", puzzle: "ZORÁN APÁM HÍTTE" },
    { category: "Közmondás", puzzle: "AZ ÉLET NEM HABOSTORTA" },
    { category: "Irodalom", puzzle: "LÁZÁR ERVIN A HÉTSZÍNvirág" },
    { category: "Tudomány", puzzle: "AZ ősrobbanás elmélete" },
    { category: "Márkanév", puzzle: "TIBI CSOKI" },
    { category: "Élőlény", puzzle: "NAGY KÓCSAG" },
    { category: "Mindennapi élet", puzzle: "ELFELEJTETTEM BEVÁSÁROLNI" },
    { category: "Tárgy", puzzle: "RADÍRGUMI" },
    { category: "Étel & Ital", puzzle: "ARANYGALUSKA VANÍLIAÖNTETTEL" },
    { category: "Film", puzzle: "AZ ÖTÖDIK ELEM" },
    { category: "Sport", puzzle: "TRIATLON" },
    { category: "Híres Ember", puzzle: "SINKOVITS IMRE" },
    { category: "Földrajz", puzzle: "A TÁTRA HEGYSÉG" },
    { category: "Történelem", puzzle: "AZ IPARI FORRADALOM" },
    { category: "Zene", puzzle: "MÁTÉ PÉTER ELMEGYEK" },
    { category: "Közmondás", puzzle: "SOK JÓ EMBER KIS HELYEN IS ELFÉR" },
    { category: "Irodalom", puzzle: "Gárdonyi GÉZA A LÁTHATATLAN EMBER" },
    { category: "Tudomány", puzzle: "A FÚZIÓS ENERGIA" },
    { category: "Márkanév", puzzle: "BÉRES CSEPP" },
    { category: "Élőlény", puzzle: "DENEVER" },
    { category: "Mindennapi élet", puzzle: "MEGHÚZTAM A LOTTÓT" },
    { category: "Tárgy", puzzle: "FOGPISZKÁLÓ" },
    { category: "Étel & Ital", puzzle: "HORTBÁGYI HÚSOS PALACSINTA" },
    { category: "Film", puzzle: "AVATAR" },
    { category: "Sport", puzzle: "VÍVÁS" },
    { category: "Híres Ember", puzzle: "KERN ANDRÁS" },
    { category: "Földrajz", puzzle: "A SZENTPÉTERVÁRI ERMITÁZS" },
    { category: "Történelem", puzzle: "A KOLDUSOK FORRADALMA" },
    { category: "Zene", puzzle: "PRESSER GÁBOR A NAGY TALÁLKOZÁS" },
    { category: "Közmondás", puzzle: "A TÉVEDÉS JOGA FENNTARTVA" },
    { category: "Irodalom", puzzle: "TAMÁSI ÁRON ÁBEL A RENGETEGBEN" },
    { category: "Tudomány", puzzle: "A SÖTÉT ANYAG REJTÉLYE" },
    { category: "Márkanév", puzzle: "SOPRONI" },
    { category: "Élőlény", puzzle: "Tengeri teknős" },
    { category: "Mindennapi élet", puzzle: "ELÁZTAM AZ ESŐBEN" },
    { category: "Tárgy", puzzle: "PÉNZTÁRCA" },
    { category: "Étel & Ital", puzzle: "JÓKAI BABLEVES" },
    { category: "Film", puzzle: "FORREST GUMP" },
    { category: "Sport", puzzle: "BIRKÓZÁS" },
    { category: "Híres Ember", puzzle: "BENKŐ LÁSZLÓ" },
    { category: "Földrajz", puzzle: "LONDON" },
    { category: "Történelem", puzzle: "AZ ARANY HORDA" },
    { category: "Zene", puzzle: "CSÍK ZENEKAR MOST A MENNYBŐL AZ ANGYAL" },
    { category: "Közmondás", puzzle: "A SZOKÁS RABJA" },
    { category: "Irodalom", puzzle: "PASSUTH LÁSZLÓ ESŐISTEN SÍR A MEXIKÓI FENNSÍKON" },
    { category: "Tudomány", puzzle: "AZ EMBERI AGY MŰKÖDÉSE" },
    { category: "Márkanév", puzzle: "SZEGEDI PAPRIKA" },
    { category: "Élőlény", puzzle: "VÖRÖS MÓKUS" },
    { category: "Mindennapi élet", puzzle: "CSAK A TELEFON VILÁGÍT" },
    { category: "Tárgy", puzzle: "ZSEBLÁMPA" },
    { category: "Étel & Ital", puzzle: "SZATMÁRI SZILVAPÁLINKA" },
    { category: "Film", puzzle: "A KENGYEL" },
    { category: "Sport", puzzle: "ÖTTUSA" },
    { category: "Híres Ember", puzzle: "CORTES HERNÁN" },
    { category: "Földrajz", puzzle: "A SZENT LÁSZLÓ TÉR" },
    { category: "Történelem", puzzle: "AZ ÓKORI RÓMA" },
    { category: "Zene", puzzle: "DEMJÉN FERENC SZERELEMVONAT" },
    { category: "Közmondás", puzzle: "A CSEBERBŐL VEDERBE" },
    { category: "Irodalom", puzzle: "WEÖRES SÁNDOR A TELJESSÉG FELÉ" },
    { category: "Tudomány", puzzle: "A VILÁGEGYETEM TÁGULÁSA" },
    { category: "Márkanév", puzzle: "KALOCSAI PAPRIKA" },
    { category: "Élőlény", puzzle: "FÜLESBAGOLY" },
    { category: "Mindennapi élet", puzzle: "NEM ÉREM EL A VONATOT" },
    { category: "Tárgy", puzzle: "SEPRŰ" },
    { category: "Étel & Ital", puzzle: "BÉLSZÍN ROLÓ" },
    { category: "Film", puzzle: "A KESELYŰ HÁROM NAPJA" },
    { category: "Sport", puzzle: "CSELGÁNCS" },
    { category: "Híres Ember", puzzle: "KARAJAN HERBERT VON" },
    { category: "Földrajz", puzzle: "PÁRIZS NOTRE DAME" },
    { category: "Történelem", puzzle: "A HUSZITA HÁBORÚK" },
    { category: "Zene", puzzle: "NEOTON FAMÍLIA DON QUIJOTE" },
    { category: "Közmondás", puzzle: "A KUTYÁT SEM ÉRDEKLI" },
    { category: "Irodalom", puzzle: "GERGELY ÁGNES A TOLMÁCS" },
    { category: "Tudomány", puzzle: "A CSILLAGOK ÉLETCIKLUSA" },
    { category: "Márkanév", puzzle: "MÁV" },
    { category: "Élőlény", puzzle: "SZALAMANDRA" },
    { category: "Mindennapi élet", puzzle: "KIÉGETT AZ IZZÓ" },
    { category: "Tárgy", puzzle: "CSIPESZ" },
    { category: "Étel & Ital", puzzle: "OROSZ KRÉMTORTA" },
    { category: "Film", puzzle: "VAN, AKI FORRÓN SZERETI" },
    { category: "Sport", puzzle: "GOKART" },
    { category: "Híres Ember", puzzle: "KUBALA LÁSZLÓ" },
    { category: "Földrajz", puzzle: "A HIMALÁJA" },
    { category: "Történelem", puzzle: "A TIZENHÁROM ARADI VÉRTANÚ" },
    { category: "Zene", puzzle: "V MOTO ROCK VÁRJ MÍG FELKEL MAJD A NAP" },
    { category: "Közmondás", puzzle: "A BUTASÁG FÁJ" },
    { category: "Irodalom", puzzle: "ASIMOV ALAPÍTVÁNY" },
    { category: "Tudomány", puzzle: "A HŐTÁGULÁS JELENSÉGE" },
    { category: "Márkanév", puzzle: "BKV" },
    { category: "Élőlény", puzzle: "CSIGA" },
    { category: "Mindennapi élet", puzzle: "NINCS TÜRELMEM VÁRNI" },
    { category: "Tárgy", puzzle: "KALAPÁCS" },
    { category: "Étel & Ital", puzzle: "TEJFÖLÖS GOMBAPAPRIKÁS" },
    { category: "Film", puzzle: "PSYCHO" },
    { category: "Sport", puzzle: "SÚLYEMELÉS" },
    { category: "Híres Ember", puzzle: "KODOLÁNYI JÁNOS" },
    { category: "Földrajz", puzzle: "A FERTŐ TÓ" },
    { category: "Történelem", puzzle: "A SZENT SZÖVETSÉG" },
    { category: "Zene", puzzle: "HOOLIGANS KIRÁLYLÁNY" },
    { category: "Közmondás", puzzle: "A SZÉPSÉG ÁRA" },
    { category: "Irodalom", puzzle: "TOLSZTOJ ANNA KARENINA" },
    { category: "Tudomány", puzzle: "AZ ELEKTROMÁGNESES INDUKCIÓ" },
    { category: "Márkanév", puzzle: "VOLÁNBUSZ" },
    { category: "Élőlény", puzzle: "BÉKA" },
    { category: "Mindennapi élet", puzzle: "ELFOGYOTT A WC PAPÍR" },
    { category: "Tárgy", puzzle: "FOGÓ" },
    { category: "Étel & Ital", puzzle: "CSOKOLÁDÉS MUFFIN" },
    { category: "Film", puzzle: "AZ ÉLET SZÉP" },
    { category: "Sport", puzzle: "MAGASUGRÁS" },
    { category: "Híres Ember", puzzle: "KULKA JÁNOS" },
    { category: "Földrajz", puzzle: "MACHU PICCHU" },
    { category: "Történelem", puzzle: "A PELOPONNÉSZOSZI HÁBORÚ" },
    { category: "Zene", puzzle: "OCHO MACHO JÓ NEKEM" },
    { category: "Közmondás", puzzle: "VERI AZ ÖRDÖG A FELESÉGÉT" },
    { category: "Irodalom", puzzle: "HEMINGWAY AZ ÖREG HALÁSZ ÉS A TENGER" },
    { category: "Tudomány", puzzle: "A DOPPLER HATÁS" },
    { category: "Márkanév", puzzle: "TEVA" },
    { category: "Élőlény", puzzle: "GYÍK" },
    { category: "Mindennapi élet", puzzle: "NEM TUDOM MIT VEGYEK FEL" },
    { category: "Tárgy", puzzle: "VÁLLFA" },
    { category: "Étel & Ital", puzzle: "SAJTTORTA" },
    { category: "Film", puzzle: "PONYVAREGÉNY" },
    { category: "Sport", puzzle: "TÁVOLUGRÁS" },
    { category: "Híres Ember", puzzle: "LORÁNFFY ZSUZSANNA" },
    { category: "Földrajz", puzzle: "STONEHENGE" },
    { category: "Törtélelem", puzzle: "A PÜNKÖSDI KIRÁLYSÁG" },
    { category: "Zene", puzzle: "PUNNANY MASSIF ÉLVEZD" },
    { category: "Közmondás", puzzle: "SZEMET SZEMÉRT FOGAT FOGÉRT" },
    { category: "Irodalom", puzzle: "MÁRAI SÁNDOR A GYERTYÁK CSONKIG ÉGNEK" },
    { category: "Tudomány", puzzle: "A Higgs-bozon" },
    { category: "Márkanév", puzzle: "EGIS" },
    { category: "Élőlény", puzzle: "SÜN" },
    { category: "Mindennapi élet", puzzle: "FÁJ A FEJEM" },
    { category: "Tárgy", puzzle: "PÁRNA" },
    { category: "Étel & Ital", puzzle: "Feketeerdő torta" },
    { category:: "Film", puzzle: "A BÁRÁNYOK HALLGATNAK" },
    { category: "Sport", puzzle: "RÖPLABDA" },
    { category: "Híres Ember", puzzle: "NAGY IMRE" },
    { category: "Földrajz", puzzle: "HAWAII SZIGETEK" },
    { category: "Történelem", puzzle: "A HÉT VEZÉR" },
    { category: "Zene", puzzle: "ANNA AND THE BARBIES MÁRTi" },
    { category: "Közmondás", puzzle: "NINCS ÚJ A NAP ALATT" },
    { category: "Irodalom", puzzle: "DOSZTOJEVSZKIJ BŰN ÉS BŰNHŐDÉS" },
    { category: "Tudomány", puzzle: "AZ ÜVEGHÁZHATÁS" },
    { category: "Márkanév", puzzle: "WIZZ AIR" },
    { category: "Élőlény", puzzle: "VAKOND" },
    { category: "Mindennapi élet", puzzle: "NINCS KEDVEM SEMMIHEZ" },
    { category: "Tárgy", puzzle: "TAKARÓ" },
    { category: "Étel & Ital", puzzle: "SZUSHI" },
    { category: "Film", puzzle: "SCHINDLER LISTÁJA" },
    { category: "Sport", puzzle: "SÍELÉS" },
    { category: "Híres Ember", puzzle: "ZRÍNYI ILONA" },
    { category: "Földrajz", puzzle: "AZ ÉSZAKI SARK" },
    { category: "Történelem", puzzle: "A SZIGETVÁRI OSTROM" },
    { category: "Zene", puzzle: "WELLHELLO RAKPART" },
    { category: "Közmondás", puzzle: "AKI MER AZ NYER" },
    { category: "Irodalom", puzzle: "TÉREY JÁNOS KÁLI HOLTAK" },
    { category: "Tudomány", puzzle: "AZ ÓZONRÉTEG" },
    { category: "Márkanév", puzzle: "RYANAIR" },
    { category: "Élőlény", puzzle: "BORZ" },
    { category: "Mindennapi élet", puzzle: "MAJD HOLNAP MEGOLDOM" },
    { category: "Tárgy", puzzle: "FÉSŰ" },
    { category: "Étel & Ital", puzzle: "GYÜMÖLCSLEVES" },
    { category: "Film", puzzle: "A ZONGORISTA" },
    { category: "Sport", puzzle: "SNOWBOARD" },
    { category: "Híres Ember", puzzle: "BÁTHORY ERZSÉBET" },
    { category: "Földrajz", puzzle: "AZ ORINOCO FOLYÓ" },
    { category: "Történelem", puzzle: "A DOZSA PARASZTHÁBORÚ" },
    { category: "Zene", puzzle: "MAGNA CUM LAUDE VIDÉKI SANZON" },
    { category: "Közmondás", puzzle: "AZ ERŐ LEGYEN VELED" },
    { category: "Irodalom", puzzle: "ECO A RÓZSA NEVE" },
    { category: "Tudomány", puzzle: "A RADIOAKTÍV SUgárzás" },
    { category: "Márkanév", puzzle: "PREZI" },
    { category: "Élőlény", puzzle: "VIDRA" },
    { category: "Mindennapi élet", puzzle: "IDEJE LENNE RENDET RAKNI" },
    { category: "Tárgy", puzzle: "KÉPKERET" },
    { category: "Étel & Ital", puzzle: "RÁNTOTT CSIRKECOMB" },
    { category: "Film", puzzle: "A SÖTÉT LOVAG" },
    { category: "Sport", puzzle: "GÖRDESZKA" },
    { category: "Híres Ember", puzzle: "MÁTYÁS KIRÁLY" },
    { category: "Földrajz", puzzle: "A SVÁJCI ALPOK" },
    { category: "Történelem", puzzle: "A KERESZTES HÁBORÚK" },
    { category: "Zene", puzzle: "COLDPLAY VIVA LA VIDA" },
    { category: "Közmondás", puzzle: "A SOKASÁG BÖLCSESSÉGE" },
    { category: "Irodalom", puzzle: "BORGES A KÉPZELT LÉNYEK KÖNYVE" },
    { category: "Tudomány", puzzle: "A SZUPERNOVA ROBBANÁS" },
    { category: "Márkanév", puzzle: "LOGMEIN" },
    { category: "Élőlény", puzzle: "HARKÁLY" },
    { category: "Mindennapi élet", puzzle: "MA ESTE FILMET NÉZÜNK" },
    { category: "Tárgy", puzzle: "SZŐNYEG" },
    { category: "Étel & Ital", puzzle: "MADÁRTEJ" },
    { category: "Film", puzzle: "GLADIÁTOR" },
    { category: "Sport", puzzle: "KERÉKPÁROZÁS" },
    { category: "Híres Ember", puzzle: "HUNYADI JÁNOS" },
    { category: "Földrajz", puzzle: "A FÜLÖP SZIGETEK" },
    { category: "Történelem", puzzle: "AZ ELSŐ EMBER A HOLDON" },
    { category: "Zene", puzzle: "IMAGINE DRAGONS BELIEVER" },
    { category: "Közmondás", puzzle: "CSAK IDŐ KÉRDÉSE" },
    { category: "Irodalom", puzzle: "KAFKA A PÖR" },
    { category: "Tudomány", puzzle: "A FÖLD MÁGNESES MEZŐJE" },
    { category: "Márkanév", puzzle: "NANUSHKA" },
    { category: "Élőlény", puzzle: "VARJÚ" },
    { category: "Mindennapi élet", puzzle: "LEKÉSTEM A TALÁLKOZÓT" },
    { category: "Tárgy", puzzle: "FÜGGÖNY" },
    { category: "Étel & Ital", puzzle: "GRÍZES TÉSZTA" },
    { category: "Film", puzzle: "A HALÁSZ KIRÁLY LEGENDÁJA" },
    { category: "Sport", puzzle: "SZÖRFÖZÉS" },
    { category: "Híres Ember", puzzle: "SZENT ISTVÁN KIRÁLY" },
    { category: "Földrajz", puzzle: "AZ AMAZONAS FOLYÓ" },
    { category: "Történelem", puzzle: "A SPANYOL INKVIZÍCIÓ" },
    { category: "Zene", puzzle: "TAYLOR SWIFT SHAKE IT OFF" },
    { category: "Közmondás", puzzle: "A CSEND ARANY" },
    { category: "Irodalom", puzzle: "CAMUS A PESTIS" },
    { category: "Tudomány", puzzle: "A FÉREGJÁRAT ELMÉLETE" },
    { category: "Márkanév", puzzle: "GRAPHISOFT" },
    { category: "Élőlény", puzzle: "FARKAS" },
    { category: "Mindennapi élet", puzzle: "ELFÁRADTAM A MUNKÁBAN" },
    { category: "Tárgy", puzzle: "KUKTA" },
    { category: "Étel & Ital", puzzle: "SZÉKELYKÁPOSZTA" },
    { category: "Film", puzzle: "VÉGSŐ ÁLLOMÁS" },
    { category: "Sport", puzzle: "BÚVÁRKODÁS" },
    { category: "Híres Ember", puzzle: "ÁRPÁD VEZÉR" },
    { category: "Földrajz", puzzle: "A NÍLUS FOLYÓ" },
    { category: "Történelem", puzzle: "A FEKETE HALÁL" },
    { category: "Zene", puzzle: "ED SHEERAN SHAPE OF YOU" },
    { category: "Közmondás", puzzle: "A PÉNZ NEM BOLDOGÍT" },
    { category: "Irodalom", puzzle: "SOLZHENITSYN A GULAG SZIGETVILÁG" },
    { category: "Tudomány", puzzle: "A TUDOMÁNYOS MÓDSZER" },
    { category: "Márkanév", puzzle: "UDS" },
    { category: "Élőlény", puzzle: "MEDÚZA" },
    { category: "Mindennapi élet", puzzle: "SIKERÜLT A VIZSGÁM" },
    { category: "Tárgy", puzzle: "TURMIXGÉP" },
    { category: "Étel & Ital", puzzle: "RIZOTTÓ" },
    { category: "Film", puzzle: "JURASSIC PARK" },
    { category: "Sport", puzzle: "EVEZÉS" },
    { category: "Híres Ember", puzzle: "ATTILA A HUN" },
    { category: "Földrajz", puzzle: "SZICÍLIA" },
    { category: "Történelem", puzzle: "A SZÁZÉVES HÁBORÚ" },
    { category: "Zene", puzzle: "BEYONCÉ SINGLE LADIES" },
    { category: "Közmondás", puzzle: "A VÉR NEM VÁLIK VÍZZÉ" },
    { category: "Irodalom", puzzle: "HUXLEY SZÉP ÚJ VILÁG" },
    { category: "Tudomány", puzzle: "A KLÍMAVÁLTOZÁS" },
    { category: "Márkanév", puzzle: "DIAGEO" },
    { category: "Élőlény", puzzle: "POLIP" },
    { category: "Mindennapi élet", puzzle: "MEGJÖTT A CSOMAGOM" },
    { category: "Tárgy", puzzle: "KENYÉRPIRÍTÓ" },
    { category: "Étel & Ital", puzzle: "LASAGNE" },
    { category: "Film", puzzle: "ALIEN" },
    { category: "Sport", puzzle: "HEGYMÁSZÁS" },
    { category: "Híres Ember", puzzle: "KÁLVIN JÁNOS" },
    { category: "Földrajz", puzzle: "ÍRORSZÁG" },
    { category: "Történelem", puzzle: "A LUSZTÁCIÓ" },
    { category: "Zene", puzzle: "RIHANNA UMBRELLA" },
    { category: "Közmondás", puzzle: "A KOCKA EL VAN VETVE" },
    { category: "Irodalom", puzzle: "BRADBURY FAHRENHEIT NÉGYSZÁZÖTVENEGY" },
    { category: "Tudomány", puzzle: "A SZEIZMOLÓGIA" },
    { category: "Márkanév", puzzle: "ROCHE" },
    { category: "Élőlény", puzzle: "KENGURU" },
    { category: "Mindennapi élet", puzzle: "NE HARAGUDJ HOGY KÉSTEM" },
    { category: "Tárgy", puzzle: "SZENDVICSSÜTŐ" },
    { category: "Étel & Ital", puzzle: "CEASAR SALÁTA" },
    { category: "Film", puzzle: "AZ UTOLSÓ SZAMURÁJ" },
    { category: "Sport", puzzle: "ÍJÁSZAT" },
    { category: "Híres Ember", puzzle: "LUTHER MÁRTON" },
    { category: "Földrajz", puzzle: "SKÓCIA" },
    { category: "Történelem", puzzle: "A NÉPVÁNDORLÁS KORA" },
    { category: "Zene", puzzle: "KATY PERRY FIREWORK" },
    { category: "Közmondás", puzzle: "AMI KÉSIK NEM MÚLIK" },
    { category: "Irodalom", puzzle: "BULGAKOV A MESTER ÉS MARGARITA" },
    { category: "Tudomány", puzzle: "A VULKANOLÓGIA" },
    { category: "Márkanév", puzzle: "NOVARTIS" },
    { category: "Élőlény", puzzle: "KOALA" },
    { category: "Mindennapi élet", puzzle: "MENJÜNK EL SÉTÁLNI" },
    { category: "Tárgy", puzzle: "GOFRISÜTŐ" },
    { category: "Étel & Ital", puzzle: "CHURROS" },
    { category: "Film", puzzle: "A RETTEGÉS FOKA" },
    { category: "Sport", puzzle: "LOVAGLÁS" },
    { category: "Híres Ember", puzzle: "SZOKRATÉSZ" },
    { category: "Földrajz", puzzle: "GÖRÖGORSZÁG" },
    { category: "Történelem", puzzle: "A BIZÁNCI BIRODALOM" },
    { category: "Zene", puzzle: "LADY GAGA BAD ROMANCE" },
    { category: "Közmondás", puzzle: "A SZÜKSÉG NAGY ÚR" },
    { category: "Irodalom", puzzle: "POE A MORGUE UTCai KETTŐS GYILKOSSÁG" },
    { category: "Tudomány", puzzle: "A PALEONTOLÓGIA" },
    { category: "Márkanév", puzzle: "PFIZER" },
    { category: "Élőlény", puzzle: "Gepárd" },
    { category: "Mindennapi élet", puzzle: "MEG KELL JAVÍTANI A CSAPOT" },
    { category: "Tárgy", puzzle: "FŰNYÍRÓ" },
    { category: "Étel & Ital", puzzle: "TACO" },
    { category: "Film", puzzle: "ÉRZELMEK HULLÁMÁN" },
    { category: "Sport", puzzle: "GOLF" },
    { category: "Híres Ember", puzzle: "PLATÓN" },
    { category: "Földrajz", puzzle: "EGYIPTOM" },
    { category: "Történelem", puzzle: "AZ OSZMÁN BIRODALOM" },
    { category: "Zene", puzzle: "JUSTIN BIEBER BABY" },
    { category: "Közmondás", puzzle: "NEM ZÖRÖG A HARASZT" },
    { category: "Irodalom", puzzle: "DOYLE SHERLOCK HOLMES" },
    { category: "Tudomány", puzzle: "AZ ARCHEOLÓGIA" },
    { category: "Márkanév", puzzle: "JOHNSON AND JOHNSON" },
    { category: "Élőlény", puzzle: "ELEFÁNT" },
    { category: "Mindennapi élet", puzzle: "RENDELJÜNK PIZZÁT" },
    { category: "Tárgy", puzzle: "LOMBSZÍVÓ" },
    { category: "Étel & Ital", puzzle: "BURRITO" },
    { category: "Film", puzzle: "A PROFESSZOR" },
    { category: "Sport", puzzle: "TENISZ" },
    { category: "Híres Ember", puzzle: "ARISZTOTELÉSZ" },
    { category: "Földrajz", puzzle: "KÍNA" },
    { category: "Történelem", puzzle: "A MONGOL BIRODALOM" },
    { category: "Zene", puzzle: "MILEY CYRUS WRECKING BALL" },
    { category: "Közmondás", puzzle: "Aki keres az talál" },
    { category: "Irodalom", puzzle: "CHRISTIE TÍZ KICSI NÉGER" },
    { category: "Tudomány", puzzle: "AZ ANTROPOLÓGIA" },
    { category: "Márkanév", puzzle: "BAYER" },
    { category: "Élőlény", puzzle: "TEVE" },
    { category: "Mindennapi élet", puzzle: "MINDJÁRT KÉSZ A VACSORA" },
    { category: "Tárgy", puzzle: "SÖVÉNYVÁGÓ" },
    { category: "Étel & Ital", puzzle: "QUESADILLA" },
    { category: "Film", puzzle: "AZ ÁRVA" },
    { category: "Sport", puzzle: "ASZTALITENISZ" },
    { category: "Híres Ember", puzzle: "NAGY SÁNDOR" },
    { category: "Földrajz", puzzle: "INDIA" },
    { category: "Történelem", puzzle: "A PERZSA BIRODALOM" },
    { category: "Zene", puzzle: "BRUNO MARS UPTOWN FUNK" },
    { category: "Közmondás", puzzle: "ADDIG NYÚJTÓZKODJ AMEDDIG A TAKARÓD ÉR" },
    { category: "Irodalom", puzzle: "KING A RAGYOGÁS" },
    { category: "Tudomány", puzzle: "A SZOCIOLÓGIA" },
    { category: "Márkanév", puzzle: "ASTRAZENECA" },
    { category: "Élőlény", puzzle: "VÍZILÓ" },
    { category: "Mindennapi élet", puzzle: "NEM TUDOM A VÁLASZT" },
    { category: "Tárgy", puzzle: "LÁNCFŰRÉSZ" },
    { category: "Étel & Ital", puzzle: "NACHOS" },
    { category: "Film", puzzle: "A SZÁLLÍTÓ" },
    { category: "Sport", puzzle: "TOLLASLABDA" },
    { category: "Híres Ember", puzzle: "HANNIBAL" },
    { category: "Földrajz", puzzle: "OROSZORSZÁG" },
    { category: "Történelem", puzzle: "A BRIT BIRODALOM" },
    { category: "Zene", puzzle: "PHARRELL WILLIAMS HAPPY" },
    { category: "Közmondás", puzzle: "INOG A FÖLD A LÁBA ALATT" },
    { category: "Irodalom", puzzle: "TOLKIEN A HOBBIT" },
    { category: "Tudomány", puzzle: "A KÖZGAZDASÁGTAN" },
    { category: "Márkanév", puzzle: "MODERNA" },
    { category: "Élőlény", puzzle: "ORRSZARVÚ" },
    { category: "Mindennapi élet", puzzle: "SZERETLEK" }
];
